In [1]:
import pandas as pd
data = pd.DataFrame({'level':['junior','Mid-level','Senior'],
                     'salary':[7500,14500,18200],
                     'position':['Data Analyst','Data Engineer','Data Scientiest']})

In [2]:
data.head()

       level  salary         position
0     junior    7500     Data Analyst
1  Mid-level   14500    Data Engineer
2     Senior   18200  Data Scientiest

In [3]:
file_path = 'database.db'

In [4]:
import os
if os.path.exists(file_path):
    try:
        os.remove(file_path)
        print(f"File {file_path} deleted successfully !")
    except Exception as e:
        print(f"Error deleting the file {file_path}.Details:{e}")
else:
    print(f"File {file_path} not found .")

File database.db deleted successfully !

In [5]:
import sqlite3

In [6]:
con = sqlite3.connect('database.db')
data.to_sql('employee', con, if_exists='replace', index=False)
# con.close()

3

In [7]:
%load_ext sql

In [8]:
%sql sqlite:///database.db

In [9]:
%reload_ext sql
%config SqlMagic.style = 'DEFAULT' 
%sql sqlite:///database.db

In [13]:
from prettytable import PrettyTable, TableStyle

In [14]:
table = PrettyTable()
table.set_style(TableStyle.DEFAULT)

In [15]:
%%sql
SELECT * FROM employee;

 * sqlite:///database.db
Done.

[('junior', 7500, 'Data Analyst'),
 ('Mid-level', 14500, 'Data Engineer'),
 ('Senior', 18200, 'Data Scientiest')]

In [18]:
%%sql
SELECT COUNT(*) FROM employee

 * sqlite:///database.db
Done.

[(3,)]

In [23]:
%%sql
SELECT ROUND(AVG(salary),2) AS AVG_SALARY FROM employee

 * sqlite:///database.db
Done.

[(13400.0,)]

In [24]:
df = pd.read_csv("E:\ANALYTICSWITHANAD\python\dataset.csv")

In [25]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,1,103,30,38,83,43.3,0.183,33,0
1,1,115,70,30,96,34.6,0.529,32,1
2,3,126,88,41,235,39.3,0.704,27,0
3,8,99,84,0,0,35.4,0.388,50,0
4,7,196,90,0,0,39.8,0.451,41,1

In [26]:
df.shape

(768, 9)

In [27]:
df.to_sql('diebetes',con, if_exists='replace', index=False)

768

In [29]:
%%sql
SELECT * FROM diebetes

 * sqlite:///database.db
Done.

[(1, 103, 30, 38, 83, 43.3, 0.183, 33, 0),
 (1, 115, 70, 30, 96, 34.6, 0.529, 32, 1),
 (3, 126, 88, 41, 235, 39.3, 0.704, 27, 0),
 (8, 99, 84, 0, 0, 35.4, 0.388, 50, 0),
 (7, 196, 90, 0, 0, 39.8, 0.451, 41, 1),
 (6, 148, 72, 35, 0, 33.6, 0.627, 50, 1),
 (1, 85, 66, 29, 0, 26.6, 0.351, 31, 0),
 (8, 183, 64, 0, 0, 23.3, 0.672, 32, 1),
 (1, 89, 66, 23, 94, 28.1, 0.167, 21, 0),
 (0, 137, 40, 35, 168, 43.1, 2.288, 33, 1),
 (5, 116, 74, 0, 0, 25.6, 0.201, 30, 0),
 (3, 78, 50, 32, 88, 31.0, 0.248, 26, 1),
 (10, 115, 0, 0, 0, 35.3, 0.134, 29, 0),
 (2, 197, 70, 45, 543, 30.5, 0.158, 53, 1),
 (8, 125, 96, 0, 0, 0.0, 0.232, 54, 1),
 (4, 110, 92, 0, 0, 37.6, 0.191, 30, 0),
 (10, 168, 74, 0, 0, 38.0, 0.537, 34, 1),
 (10, 139, 80, 0, 0, 27.1, 1.441, 57, 0),
 (1, 189, 60, 23, 846, 30.1, 0.398, 59, 1),
 (5, 166, 72, 19, 175, 25.8, 0.587, 51, 1),
 (7, 100, 0, 0, 0, 30.0, 0.484, 32, 1),
 (0, 118, 84, 47, 230, 45.8, 0.551, 31, 1),
 (7, 107, 74, 0, 0, 29.6, 0.254, 31, 1),
 (9, 119, 80, 35, 0, 29.0, 0.263, 29, 1),
 (11, 143, 94, 33, 146, 36.6, 0.254, 51, 1),
 (10, 125, 70, 26, 115, 31.1, 0.205, 41, 1),
 (7, 147, 76, 0, 0, 39.4, 0.257, 43, 1),
 (1, 97, 66, 15, 140, 23.2, 0.487, 22, 0),
 (13, 145, 82, 19, 110, 22.2, 0.245, 57, 0),
 (5, 117, 92, 0, 0, 34.1, 0.337, 38, 0),
 (5, 109, 75, 26, 0, 36.0, 0.546, 60, 0),
 (3, 158, 76, 36, 245, 31.6, 0.851, 28, 1),
 (3, 88, 58, 11, 54, 24.8, 0.267, 22, 0),
 (6, 92, 92, 0, 0, 19.9, 0.188, 28, 0),
 (10, 122, 78, 31, 0, 27.6, 0.512, 45, 0),
 (4, 103, 60, 33, 192, 24.0, 0.966, 33, 0),
 (11, 138, 76, 0, 0, 33.2, 0.42, 35, 0),
 (9, 102, 76, 37, 0, 32.9, 0.665, 46, 1),
 (2, 90, 68, 42, 0, 38.2, 0.503, 27, 1),
 (4, 111, 72, 47, 207, 37.1, 1.39, 56, 1),
 (3, 180, 64, 25, 70, 34.0, 0.271, 26, 0),
 (7, 133, 84, 0, 0, 40.2, 0.696, 37, 0),
 (7, 106, 92, 18, 0, 22.7, 0.235, 48, 0),
 (9, 171, 110, 24, 240, 45.4, 0.721, 54, 1),
 (7, 159, 64, 0, 0, 27.4, 0.294, 40, 0),
 (0, 180, 66, 39, 0, 42.0, 1.893, 25, 1),
 (1, 146, 56, 0, 0, 29.7, 0.564, 29, 0),
 (2, 71, 70, 27, 0, 28.0, 0.586, 22, 0),
 (7, 103, 66, 32, 0, 39.1, 0.344, 31, 1),
 (7, 105, 0, 0, 0, 0.0, 0.305, 24, 0),
 (1, 103, 80, 11, 82, 19.4, 0.491, 22, 0),
 (1, 101, 50, 15, 36, 24.2, 0.526, 26, 0),
 (5, 88, 66, 21, 23, 24.4, 0.342, 30, 0),
 (8, 176, 90, 34, 300, 33.7, 0.467, 58, 1),
 (7, 150, 66, 42, 342, 34.7, 0.718, 42, 0),
 (1, 73, 50, 10, 0, 23.0, 0.248, 21, 0),
 (7, 187, 68, 39, 304, 37.7, 0.254, 41, 1),
 (0, 100, 88, 60, 110, 46.8, 0.962, 31, 0),
 (0, 146, 82, 0, 0, 40.5, 1.781, 44, 0),
 (0, 105, 64, 41, 142, 41.5, 0.173, 22, 0),
 (2, 84, 0, 0, 0, 0.0, 0.304, 21, 0),
 (8, 133, 72, 0, 0, 32.9, 0.27, 39, 1),
 (5, 44, 62, 0, 0, 25.0, 0.587, 36, 0),
 (2, 141, 58, 34, 128, 25.4, 0.699, 24, 0),
 (7, 114, 66, 0, 0, 32.8, 0.258, 42, 1),
 (5, 99, 74, 27, 0, 29.0, 0.203, 32, 0),
 (0, 109, 88, 30, 0, 32.5, 0.855, 38, 1),
 (2, 109, 92, 0, 0, 42.7, 0.845, 54, 0),
 (1, 95, 66, 13, 38, 19.6, 0.334, 25, 0),
 (4, 146, 85, 27, 100, 28.9, 0.189, 27, 0),
 (2, 100, 66, 20, 90, 32.9, 0.867, 28, 1),
 (5, 139, 64, 35, 140, 28.6, 0.411, 26, 0),
 (13, 126, 90, 0, 0, 43.4, 0.583, 42, 1),
 (4, 129, 86, 20, 270, 35.1, 0.231, 23, 0),
 (1, 79, 75, 30, 0, 32.0, 0.396, 22, 0),
 (1, 0, 48, 20, 0, 24.7, 0.14, 22, 0),
 (7, 62, 78, 0, 0, 32.6, 0.391, 41, 0),
 (5, 95, 72, 33, 0, 37.7, 0.37, 27, 0),
 (0, 131, 0, 0, 0, 43.2, 0.27, 26, 1),
 (2, 112, 66, 22, 0, 25.0, 0.307, 24, 0),
 (3, 113, 44, 13, 0, 22.4, 0.14, 22, 0),
 (2, 74, 0, 0, 0, 0.0, 0.102, 22, 0),
 (7, 83, 78, 26, 71, 29.3, 0.767, 36, 0),
 (0, 101, 65, 28, 0, 24.6, 0.237, 22, 0),
 (5, 137, 108, 0, 0, 48.8, 0.227, 37, 1),
 (2, 110, 74, 29, 125, 32.4, 0.698, 27, 0),
 (13, 106, 72, 54, 0, 36.6, 0.178, 45, 0),
 (2, 100, 68, 25, 71, 38.5, 0.324, 26, 0),
 (15, 136, 70, 32, 110, 37.1, 0.153, 43, 1),
 (1, 107, 68, 19, 0, 26.5, 0.165, 24, 0),
 (1, 80, 55, 0, 0, 19.1, 0.258, 21, 0),
 (4, 123, 80, 15, 176, 32.0, 0.443, 34, 0),
 (7, 81, 78, 40, 48, 46.7, 0.261, 42, 0),
 (4, 134, 72, 0, 0, 23.8, 0.277, 60, 1),
 (2, 142, 82, 18, 64, 24.7, 0.761, 21, 0),
 (6, 144, 72, 27, 228, 33.9, 0.255, 40, 0),
 (2, 92, 62, 28, 0, 31.6, 0.13, 24, 0),
 (1, 71, 48, 18, 76, 20.4, 0.323, 22, 0),
 (6, 93, 50, 30, 64, 28.7, 0.356, 23, 0),
 (1, 122, 90, 51, 220, 49.7, 0.325, 31, 1),
 (1, 163, 72, 0, 0, 39.0, 1.222, 33, 1),
 (1, 151, 60, 0, 0, 26.1, 0.179, 22, 0),
 (0, 125, 96, 0, 0, 22.5, 0.262, 21, 0),
 (1, 81, 72, 18, 40, 26.6, 0.283, 24, 0),
 (2, 85, 65, 0, 0, 39.6, 0.93, 27, 0),
 (1, 126, 56, 29, 152, 28.7, 0.801, 21, 0),
 (1, 96, 122, 0, 0, 22.4, 0.207, 27, 0),
 (4, 144, 58, 28, 140, 29.5, 0.287, 37, 0),
 (3, 83, 58, 31, 18, 34.3, 0.336, 25, 0),
 (0, 95, 85, 25, 36, 37.4, 0.247, 24, 1),
 (3, 171, 72, 33, 135, 33.3, 0.199, 24, 1),
 (8, 155, 62, 26, 495, 34.0, 0.543, 46, 1),
 (1, 89, 76, 34, 37, 31.2, 0.192, 23, 0),
 (4, 76, 62, 0, 0, 34.0, 0.391, 25, 0),
 (7, 160, 54, 32, 175, 30.5, 0.588, 39, 1),
 (4, 146, 92, 0, 0, 31.2, 0.539, 61, 1),
 (5, 124, 74, 0, 0, 34.0, 0.22, 38, 1),
 (5, 78, 48, 0, 0, 33.7, 0.654, 25, 0),
 (4, 97, 60, 23, 0, 28.2, 0.443, 22, 0),
 (4, 99, 76, 15, 51, 23.2, 0.223, 21, 0),
 (0, 162, 76, 56, 100, 53.2, 0.759, 25, 1),
 (6, 111, 64, 39, 0, 34.2, 0.26, 24, 0),
 (2, 107, 74, 30, 100, 33.6, 0.404, 23, 0),
 (5, 132, 80, 0, 0, 26.8, 0.186, 69, 0),
 (0, 113, 76, 0, 0, 33.3, 0.278, 23, 1),
 (1, 88, 30, 42, 99, 55.0, 0.496, 26, 1),
 (3, 120, 70, 30, 135, 42.9, 0.452, 30, 0),
 (1, 118, 58, 36, 94, 33.3, 0.261, 23, 0),
 (1, 117, 88, 24, 145, 34.5, 0.403, 40, 1),
 (0, 105, 84, 0, 0, 27.9, 0.741, 62, 1),
 (4, 173, 70, 14, 168, 29.7, 0.361, 33, 1),
 (9, 122, 56, 0, 0, 33.3, 1.114, 33, 1),
 (3, 170, 64, 37, 225, 34.5, 0.356, 30, 1),
 (8, 84, 74, 31, 0, 38.3, 0.457, 39, 0),
 (2, 96, 68, 13, 49, 21.1, 0.647, 26, 0),
 (2, 125, 60, 20, 140, 33.8, 0.088, 31, 0),
 (0, 100, 70, 26, 50, 30.8, 0.597, 21, 0),
 (0, 93, 60, 25, 92, 28.7, 0.532, 22, 0),
 (0, 129, 80, 0, 0, 31.2, 0.703, 29, 0),
 (5, 105, 72, 29, 325, 36.9, 0.159, 28, 0),
 (3, 128, 78, 0, 0, 21.1, 0.268, 55, 0),
 (5, 106, 82, 30, 0, 39.5, 0.286, 38, 0),
 (2, 108, 52, 26, 63, 32.5, 0.318, 22, 0),
 (10, 108, 66, 0, 0, 32.4, 0.272, 42, 1),
 (4, 154, 62, 31, 284, 32.8, 0.237, 23, 0),
 (0, 102, 75, 23, 0, 0.0, 0.572, 21, 0),
 (9, 57, 80, 37, 0, 32.8, 0.096, 41, 0),
 (2, 106, 64, 35, 119, 30.5, 1.4, 34, 0),
 (5, 147, 78, 0, 0, 33.7, 0.218, 65, 0),
 (2, 90, 70, 17, 0, 27.3, 0.085, 22, 0),
 (1, 136, 74, 50, 204, 37.4, 0.399, 24, 0),
 (4, 114, 65, 0, 0, 21.9, 0.432, 37, 0),
 (9, 156, 86, 28, 155, 34.3, 1.189, 42, 1),
 (1, 153, 82, 42, 485, 40.6, 0.687, 23, 0),
 (8, 188, 78, 0, 0, 47.9, 0.137, 43, 1),
 (7, 152, 88, 44, 0, 50.0, 0.337, 36, 1),
 (2, 99, 52, 15, 94, 24.6, 0.637, 21, 0),
 (1, 109, 56, 21, 135, 25.2, 0.833, 23, 0),
 (2, 88, 74, 19, 53, 29.0, 0.229, 22, 0),
 (17, 163, 72, 41, 114, 40.9, 0.817, 47, 1),
 (4, 151, 90, 38, 0, 29.7, 0.294, 36, 0),
 (7, 102, 74, 40, 105, 37.2, 0.204, 45, 0),
 (0, 114, 80, 34, 285, 44.2, 0.167, 27, 0),
 (2, 100, 64, 23, 0, 29.7, 0.368, 21, 0),
 (0, 131, 88, 0, 0, 31.6, 0.743, 32, 1),
 (6, 104, 74, 18, 156, 29.9, 0.722, 41, 1),
 (3, 148, 66, 25, 0, 32.5, 0.256, 22, 0),
 (4, 120, 68, 0, 0, 29.6, 0.709, 34, 0),
 (4, 110, 66, 0, 0, 31.9, 0.471, 29, 0),
 (3, 111, 90, 12, 78, 28.4, 0.495, 29, 0),
 (6, 102, 82, 0, 0, 30.8, 0.18, 36, 1),
 (6, 134, 70, 23, 130, 35.4, 0.542, 29, 1),
 (2, 87, 0, 23, 0, 28.9, 0.773, 25, 0),
 (1, 79, 60, 42, 48, 43.5, 0.678, 23, 0),
 (2, 75, 64, 24, 55, 29.7, 0.37, 33, 0),
 (8, 179, 72, 42, 130, 32.7, 0.719, 36, 1),
 (6, 85, 78, 0, 0, 31.2, 0.382, 42, 0),
 (0, 129, 110, 46, 130, 67.1, 0.319, 26, 1),
 (5, 143, 78, 0, 0, 45.0, 0.19, 47, 0),
 (5, 130, 82, 0, 0, 39.1, 0.956, 37, 1),
 (6, 87, 80, 0, 0, 23.2, 0.084, 32, 0),
 (0, 119, 64, 18, 92, 34.9, 0.725, 23, 0),
 (1, 0, 74, 20, 23, 27.7, 0.299, 21, 0),
 (5, 73, 60, 0, 0, 26.8, 0.268, 27, 0),
 (4, 141, 74, 0, 0, 27.6, 0.244, 40, 0),
 (7, 194, 68, 28, 0, 35.9, 0.745, 41, 1),
 (8, 181, 68, 36, 495, 30.1, 0.615, 60, 1),
 (1, 128, 98, 41, 58, 32.0, 1.321, 33, 1),
 (8, 109, 76, 39, 114, 27.9, 0.64, 31, 1),
 (5, 139, 80, 35, 160, 31.6, 0.361, 25, 1),
 (3, 111, 62, 0, 0, 22.6, 0.142, 21, 0),
 (9, 123, 70, 44, 94, 33.1, 0.374, 40, 0),
 (7, 159, 66, 0, 0, 30.4, 0.383, 36, 1),
 (11, 135, 0, 0, 0, 52.3, 0.578, 40, 1),
 (8, 85, 55, 20, 0, 24.4, 0.136, 42, 0),
 (5, 158, 84, 41, 210, 39.4, 0.395, 29, 1),
 (1, 105, 58, 0, 0, 24.3, 0.187, 21, 0),
 (3, 107, 62, 13, 48, 22.9, 0.678, 23, 1),
 (4, 109, 64, 44, 99, 34.8, 0.905, 26, 1),
 (4, 148, 60, 27, 318, 30.9, 0.15, 29, 1),
 (0, 113, 80, 16, 0, 31.0, 0.874, 21, 0),
 (1, 138, 82, 0, 0, 40.1, 0.236, 28, 0),
 (0, 108, 68, 20, 0, 27.3, 0.787, 32, 0),
 (2, 99, 70, 16, 44, 20.4, 0.235, 27, 0),
 (6, 103, 72, 32, 190, 37.7, 0.324, 55, 0),
 (5, 111, 72, 28, 0, 23.9, 0.407, 27, 0),
 (8, 196, 76, 29, 280, 37.5, 0.605, 57, 1),
 (5, 162, 104, 0, 0, 37.7, 0.151, 52, 1),
 (1, 96, 64, 27, 87, 33.2, 0.289, 21, 0),
 (7, 184, 84, 33, 0, 35.5, 0.355, 41, 1),
 (2, 81, 60, 22, 0, 27.7, 0.29, 25, 0),
 (0, 147, 85, 54, 0, 42.8, 0.375, 24, 0),
 (7, 179, 95, 31, 0, 34.2, 0.164, 60, 0),
 (0, 140, 65, 26, 130, 42.6, 0.431, 24, 1),
 (9, 112, 82, 32, 175, 34.2, 0.26, 36, 1),
 (12, 151, 70, 40, 271, 41.8, 0.742, 38, 1),
 (5, 109, 62, 41, 129, 35.8, 0.514, 25, 1),
 (6, 125, 68, 30, 120, 30.0, 0.464, 32, 0),
 (5, 85, 74, 22, 0, 29.0, 1.224, 32, 1),
 (5, 112, 66, 0, 0, 37.8, 0.261, 41, 1),
 (0, 177, 60, 29, 478, 34.6, 1.072, 21, 1),
 (2, 158, 90, 0, 0, 31.6, 0.805, 66, 1),
 (7, 119, 0, 0, 0, 25.2, 0.209, 37, 0),
 (7, 142, 60, 33, 190, 28.8, 0.687, 61, 0),
 (1, 100, 66, 15, 56, 23.6, 0.666, 26, 0),
 (1, 87, 78, 27, 32, 34.6, 0.101, 22, 0),
 (0, 101, 76, 0, 0, 35.7, 0.198, 26, 0),
 (3, 162, 52, 38, 0, 37.2, 0.652, 24, 1),
 (4, 197, 70, 39, 744, 36.7, 2.329, 31, 0),
 (0, 117, 80, 31, 53, 45.2, 0.089, 24, 0),
 (4, 142, 86, 0, 0, 44.0, 0.645, 22, 1),
 (6, 134, 80, 37, 370, 46.2, 0.238, 46, 1),
 (1, 79, 80, 25, 37, 25.4, 0.583, 22, 0),
 (4, 122, 68, 0, 0, 35.0, 0.394, 29, 0),
 (3, 74, 68, 28, 45, 29.7, 0.293, 23, 0),
 (4, 171, 72, 0, 0, 43.6, 0.479, 26, 1),
 (7, 181, 84, 21, 192, 35.9, 0.586, 51, 1),
 (0, 179, 90, 27, 0, 44.1, 0.686, 23, 1),
 (9, 164, 84, 21, 0, 30.8, 0.831, 32, 1),
 (0, 104, 76, 0, 0, 18.4, 0.582, 27, 0),
 (1, 91, 64, 24, 0, 29.2, 0.192, 21, 0),
 (4, 91, 70, 32, 88, 33.1, 0.446, 22, 0),
 (3, 139, 54, 0, 0, 25.6, 0.402, 22, 1),
 (6, 119, 50, 22, 176, 27.1, 1.318, 33, 1),
 (2, 146, 76, 35, 194, 38.2, 0.329, 29, 0),
 (9, 184, 85, 15, 0, 30.0, 1.213, 49, 1),
 (10, 122, 68, 0, 0, 31.2, 0.258, 41, 0),
 (0, 165, 90, 33, 680, 52.3, 0.427, 23, 0),
 (9, 124, 70, 33, 402, 35.4, 0.282, 34, 0),
 (1, 111, 86, 19, 0, 30.1, 0.143, 23, 0),
 (9, 106, 52, 0, 0, 31.2, 0.38, 42, 0),
 (2, 129, 84, 0, 0, 28.0, 0.284, 27, 0),
 (2, 90, 80, 14, 55, 24.4, 0.249, 24, 0),
 (0, 86, 68, 32, 0, 35.8, 0.238, 25, 0),
 (12, 92, 62, 7, 258, 27.6, 0.926, 44, 1),
 (1, 113, 64, 35, 0, 33.6, 0.543, 21, 1),
 (3, 111, 56, 39, 0, 30.1, 0.557, 30, 0),
 (2, 114, 68, 22, 0, 28.7, 0.092, 25, 0),
 (1, 193, 50, 16, 375, 25.9, 0.655, 24, 0),
 (11, 155, 76, 28, 150, 33.3, 1.353, 51, 1),
 (3, 191, 68, 15, 130, 30.9, 0.299, 34, 0),
 (3, 141, 0, 0, 0, 30.0, 0.761, 27, 1),
 (4, 95, 70, 32, 0, 32.1, 0.612, 24, 0),
 (3, 142, 80, 15, 0, 32.4, 0.2, 63, 0),
 (4, 123, 62, 0, 0, 32.0, 0.226, 35, 1),
 (5, 96, 74, 18, 67, 33.6, 0.997, 43, 0),
 (0, 138, 0, 0, 0, 36.3, 0.933, 25, 1),
 (2, 128, 64, 42, 0, 40.0, 1.101, 24, 0),
 (0, 102, 52, 0, 0, 25.1, 0.078, 21, 0),
 (2, 146, 0, 0, 0, 27.5, 0.24, 28, 1),
 (10, 101, 86, 37, 0, 45.6, 1.136, 38, 1),
 (2, 108, 62, 32, 56, 25.2, 0.128, 21, 0),
 (3, 122, 78, 0, 0, 23.0, 0.254, 40, 0),
 (1, 71, 78, 50, 45, 33.2, 0.422, 21, 0),
 (13, 106, 70, 0, 0, 34.2, 0.251, 52, 0),
 (2, 100, 70, 52, 57, 40.5, 0.677, 25, 0),
 (7, 106, 60, 24, 0, 26.5, 0.296, 29, 1),
 (0, 104, 64, 23, 116, 27.8, 0.454, 23, 0),
 (5, 114, 74, 0, 0, 24.9, 0.744, 57, 0),
 (2, 108, 62, 10, 278, 25.3, 0.881, 22, 0),
 (0, 146, 70, 0, 0, 37.9, 0.334, 28, 1),
 (10, 129, 76, 28, 122, 35.9, 0.28, 39, 0),
 (7, 133, 88, 15, 155, 32.4, 0.262, 37, 0),
 (7, 161, 86, 0, 0, 30.4, 0.165, 47, 1),
 (2, 108, 80, 0, 0, 27.0, 0.259, 52, 1),
 (7, 136, 74, 26, 135, 26.0, 0.647, 51, 0),
 (5, 155, 84, 44, 545, 38.7, 0.619, 34, 0),
 (1, 119, 86, 39, 220, 45.6, 0.808, 29, 1),
 (4, 96, 56, 17, 49, 20.8, 0.34, 26, 0),
 (5, 108, 72, 43, 75, 36.1, 0.263, 33, 0),
 (0, 78, 88, 29, 40, 36.9, 0.434, 21, 0),
 (0, 107, 62, 30, 74, 36.6, 0.757, 25, 1),
 (2, 128, 78, 37, 182, 43.3, 1.224, 31, 1),
 (1, 128, 48, 45, 194, 40.5, 0.613, 24, 1),
 (0, 161, 50, 0, 0, 21.9, 0.254, 65, 0),
 (6, 151, 62, 31, 120, 35.5, 0.692, 28, 0),
 (2, 146, 70, 38, 360, 28.0, 0.337, 29, 1),
 (0, 126, 84, 29, 215, 30.7, 0.52, 24, 0),
 (14, 100, 78, 25, 184, 36.6, 0.412, 46, 1),
 (8, 112, 72, 0, 0, 23.6, 0.84, 58, 0),
 (0, 167, 0, 0, 0, 32.3, 0.839, 30, 1),
 (2, 144, 58, 33, 135, 31.6, 0.422, 25, 1),
 (5, 77, 82, 41, 42, 35.8, 0.156, 35, 0),
 (5, 115, 98, 0, 0, 52.9, 0.209, 28, 1),
 (3, 150, 76, 0, 0, 21.0, 0.207, 37, 0),
 (2, 120, 76, 37, 105, 39.7, 0.215, 29, 0),
 (10, 161, 68, 23, 132, 25.5, 0.326, 47, 1),
 (0, 137, 68, 14, 148, 24.8, 0.143, 21, 0),
 (0, 128, 68, 19, 180, 30.5, 1.391, 25, 1),
 (2, 124, 68, 28, 205, 32.9, 0.875, 30, 1),
 (6, 80, 66, 30, 0, 26.2, 0.313, 41, 0),
 (0, 106, 70, 37, 148, 39.4, 0.605, 22, 0),
 (2, 155, 74, 17, 96, 26.6, 0.433, 27, 1),
 (3, 113, 50, 10, 85, 29.5, 0.626, 25, 0),
 (7, 109, 80, 31, 0, 35.9, 1.127, 43, 1),
 (2, 112, 68, 22, 94, 34.1, 0.315, 26, 0),
 (3, 99, 80, 11, 64, 19.3, 0.284, 30, 0),
 (3, 182, 74, 0, 0, 30.5, 0.345, 29, 1),
 (3, 115, 66, 39, 140, 38.1, 0.15, 28, 0),
 (6, 194, 78, 0, 0, 23.5, 0.129, 59, 1),
 (4, 129, 60, 12, 231, 27.5, 0.527, 31, 0),
 (3, 112, 74, 30, 0, 31.6, 0.197, 25, 1),
 (0, 124, 70, 20, 0, 27.4, 0.254, 36, 1),
 (13, 152, 90, 33, 29, 26.8, 0.731, 43, 1),
 (2, 112, 75, 32, 0, 35.7, 0.148, 21, 0),
 (1, 157, 72, 21, 168, 25.6, 0.123, 24, 0),
 (1, 122, 64, 32, 156, 35.1, 0.692, 30, 1),
 (10, 179, 70, 0, 0, 35.1, 0.2, 37, 0),
 (2, 102, 86, 36, 120, 45.5, 0.127, 23, 1),
 (6, 105, 70, 32, 68, 30.8, 0.122, 37, 0),
 (8, 118, 72, 19, 0, 23.1, 1.476, 46, 0),
 (2, 87, 58, 16, 52, 32.7, 0.166, 25, 0),
 (1, 180, 0, 0, 0, 43.3, 0.282, 41, 1),
 (12, 106, 80, 0, 0, 23.6, 0.137, 44, 0),
 (1, 95, 60, 18, 58, 23.9, 0.26, 22, 0),
 (0, 165, 76, 43, 255, 47.9, 0.259, 26, 0),
 (0, 117, 0, 0, 0, 33.8, 0.932, 44, 0),
 (5, 115, 76, 0, 0, 31.2, 0.343, 44, 1),
 (9, 152, 78, 34, 171, 34.2, 0.893, 33, 1),
 (7, 178, 84, 0, 0, 39.9, 0.331, 41, 1),
 (1, 130, 70, 13, 105, 25.9, 0.472, 22, 0),
 (1, 95, 74, 21, 73, 25.9, 0.673, 36, 0),
 (1, 0, 68, 35, 0, 32.0, 0.389, 22, 0),
 (5, 122, 86, 0, 0, 34.7, 0.29, 33, 0),
 (8, 95, 72, 0, 0, 36.8, 0.485, 57, 0),
 (8, 126, 88, 36, 108, 38.5, 0.349, 49, 0),
 (1, 139, 46, 19, 83, 28.7, 0.654, 22, 0),
 (3, 116, 0, 0, 0, 23.5, 0.187, 23, 0),
 (3, 99, 62, 19, 74, 21.8, 0.279, 26, 0),
 (5, 0, 80, 32, 0, 41.0, 0.346, 37, 1),
 (4, 92, 80, 0, 0, 42.2, 0.237, 29, 0),
 (4, 137, 84, 0, 0, 31.2, 0.252, 30, 0),
 (3, 61, 82, 28, 0, 34.4, 0.243, 46, 0),
 (1, 90, 62, 12, 43, 27.2, 0.58, 24, 0),
 (3, 90, 78, 0, 0, 42.7, 0.559, 21, 0),
 (9, 165, 88, 0, 0, 30.4, 0.302, 49, 1),
 (1, 125, 50, 40, 167, 33.3, 0.962, 28, 1),
 (13, 129, 0, 30, 0, 39.9, 0.569, 44, 1),
 (12, 88, 74, 40, 54, 35.3, 0.378, 48, 0),
 (1, 196, 76, 36, 249, 36.5, 0.875, 29, 1),
 (5, 189, 64, 33, 325, 31.2, 0.583, 29, 1),
 (5, 158, 70, 0, 0, 29.8, 0.207, 63, 0),
 (5, 103, 108, 37, 0, 39.2, 0.305, 65, 0),
 (4, 146, 78, 0, 0, 38.5, 0.52, 67, 1),
 (4, 147, 74, 25, 293, 34.9, 0.385, 30, 0),
 (5, 99, 54, 28, 83, 34.0, 0.499, 30, 0),
 (6, 124, 72, 0, 0, 27.6, 0.368, 29, 1),
 (0, 101, 64, 17, 0, 21.0, 0.252, 21, 0),
 (3, 81, 86, 16, 66, 27.5, 0.306, 22, 0),
 (1, 133, 102, 28, 140, 32.8, 0.234, 45, 1),
 (3, 173, 82, 48, 465, 38.4, 2.137, 25, 1),
 (0, 118, 64, 23, 89, 0.0, 1.731, 21, 0),
 (0, 84, 64, 22, 66, 35.8, 0.545, 21, 0),
 (2, 105, 58, 40, 94, 34.9, 0.225, 25, 0),
 (2, 122, 52, 43, 158, 36.2, 0.816, 28, 0),
 (12, 140, 82, 43, 325, 39.2, 0.528, 58, 1),
 (0, 98, 82, 15, 84, 25.2, 0.299, 22, 0),
 (1, 87, 60, 37, 75, 37.2, 0.509, 22, 0),
 (4, 156, 75, 0, 0, 48.3, 0.238, 32, 1),
 (0, 93, 100, 39, 72, 43.4, 1.021, 35, 0),
 (1, 107, 72, 30, 82, 30.8, 0.821, 24, 0),
 (0, 105, 68, 22, 0, 20.0, 0.236, 22, 0),
 (1, 109, 60, 8, 182, 25.4, 0.947, 21, 0),
 (1, 90, 62, 18, 59, 25.1, 1.268, 25, 0),
 (1, 125, 70, 24, 110, 24.3, 0.221, 25, 0),
 (1, 119, 54, 13, 50, 22.3, 0.205, 24, 0),
 (5, 116, 74, 29, 0, 32.3, 0.66, 35, 1),
 (8, 105, 100, 36, 0, 43.3, 0.239, 45, 1),
 (5, 144, 82, 26, 285, 32.0, 0.452, 58, 1),
 (3, 100, 68, 23, 81, 31.6, 0.949, 28, 0),
 (1, 100, 66, 29, 196, 32.0, 0.444, 42, 0),
 (5, 166, 76, 0, 0, 45.7, 0.34, 27, 1),
 (1, 131, 64, 14, 415, 23.7, 0.389, 21, 0),
 (4, 116, 72, 12, 87, 22.1, 0.463, 37, 0),
 (4, 158, 78, 0, 0, 32.9, 0.803, 31, 1),
 (2, 127, 58, 24, 275, 27.7, 1.6, 25, 0),
 (3, 96, 56, 34, 115, 24.7, 0.944, 39, 0),
 (0, 131, 66, 40, 0, 34.3, 0.196, 22, 1),
 (3, 82, 70, 0, 0, 21.1, 0.389, 25, 0),
 (3, 193, 70, 31, 0, 34.9, 0.241, 25, 1),
 (4, 95, 64, 0, 0, 32.0, 0.161, 31, 1),
 (6, 137, 61, 0, 0, 24.2, 0.151, 55, 0),
 (5, 136, 84, 41, 88, 35.0, 0.286, 35, 1),
 (9, 72, 78, 25, 0, 31.6, 0.28, 38, 0),
 (5, 168, 64, 0, 0, 32.9, 0.135, 41, 1),
 (2, 123, 48, 32, 165, 42.1, 0.52, 26, 0),
 (4, 115, 72, 0, 0, 28.9, 0.376, 46, 1),
 (0, 101, 62, 0, 0, 21.9, 0.336, 25, 0),
 (8, 197, 74, 0, 0, 25.9, 1.191, 39, 1),
 (1, 172, 68, 49, 579, 42.4, 0.702, 28, 1),
 (6, 102, 90, 39, 0, 35.7, 0.674, 28, 0),
 (1, 112, 72, 30, 176, 34.4, 0.528, 25, 0),
 (1, 143, 84, 23, 310, 42.4, 1.076, 22, 0),
 (1, 143, 74, 22, 61, 26.2, 0.256, 21, 0),
 (0, 138, 60, 35, 167, 34.6, 0.534, 21, 1),
 (3, 173, 84, 33, 474, 35.7, 0.258, 22, 1),
 (1, 97, 68, 21, 0, 27.2, 1.095, 22, 0),
 (4, 144, 82, 32, 0, 38.5, 0.554, 37, 1),
 (1, 83, 68, 0, 0, 18.2, 0.624, 27, 0),
 (3, 129, 64, 29, 115, 26.4, 0.219, 28, 1),
 (1, 119, 88, 41, 170, 45.3, 0.507, 26, 0),
 (2, 94, 68, 18, 76, 26.0, 0.561, 21, 0),
 (0, 102, 64, 46, 78, 40.6, 0.496, 21, 0),
 (2, 115, 64, 22, 0, 30.8, 0.421, 21, 0),
 (8, 151, 78, 32, 210, 42.9, 0.516, 36, 1),
 (4, 184, 78, 39, 277, 37.0, 0.264, 31, 1),
 (0, 94, 0, 0, 0, 0.0, 0.256, 25, 0),
 (1, 181, 64, 30, 180, 34.1, 0.328, 38, 1),
 (0, 135, 94, 46, 145, 40.6, 0.284, 26, 0),
 (1, 95, 82, 25, 180, 35.0, 0.233, 43, 1),
 (2, 99, 0, 0, 0, 22.2, 0.108, 23, 0),
 (3, 89, 74, 16, 85, 30.4, 0.551, 38, 0),
 (1, 80, 74, 11, 60, 30.0, 0.527, 22, 0),
 (2, 139, 75, 0, 0, 25.6, 0.167, 29, 0),
 (1, 90, 68, 8, 0, 24.5, 1.138, 36, 0),
 (0, 141, 0, 0, 0, 42.4, 0.205, 29, 1),
 (12, 140, 85, 33, 0, 37.4, 0.244, 41, 0),
 (5, 147, 75, 0, 0, 29.9, 0.434, 28, 0),
 (1, 97, 70, 15, 0, 18.2, 0.147, 21, 0),
 (6, 107, 88, 0, 0, 36.8, 0.727, 31, 0),
 (0, 189, 104, 25, 0, 34.3, 0.435, 41, 1),
 (2, 83, 66, 23, 50, 32.2, 0.497, 22, 0),
 (4, 117, 64, 27, 120, 33.2, 0.23, 24, 0),
 (8, 108, 70, 0, 0, 30.5, 0.955, 33, 1),
 (4, 117, 62, 12, 0, 29.7, 0.38, 30, 1),
 (0, 180, 78, 63, 14, 59.4, 2.42, 25, 1),
 (1, 100, 72, 12, 70, 25.3, 0.658, 28, 0),
 (0, 95, 80, 45, 92, 36.5, 0.33, 26, 0),
 (0, 104, 64, 37, 64, 33.6, 0.51, 22, 1),
 (0, 120, 74, 18, 63, 30.5, 0.285, 26, 0),
 (1, 82, 64, 13, 95, 21.2, 0.415, 23, 0),
 (2, 134, 70, 0, 0, 28.9, 0.542, 23, 1),
 (0, 91, 68, 32, 210, 39.9, 0.381, 25, 0),
 (2, 119, 0, 0, 0, 19.6, 0.832, 72, 0),
 (2, 100, 54, 28, 105, 37.8, 0.498, 24, 0),
 (14, 175, 62, 30, 0, 33.6, 0.212, 38, 1),
 (1, 135, 54, 0, 0, 26.7, 0.687, 62, 0),
 (5, 86, 68, 28, 71, 30.2, 0.364, 24, 0),
 (10, 148, 84, 48, 237, 37.6, 1.001, 51, 1),
 (9, 134, 74, 33, 60, 25.9, 0.46, 81, 0),
 (9, 120, 72, 22, 56, 20.8, 0.733, 48, 0),
 (1, 71, 62, 0, 0, 21.8, 0.416, 26, 0),
 (8, 74, 70, 40, 49, 35.3, 0.705, 39, 0),
 (5, 88, 78, 30, 0, 27.6, 0.258, 37, 0),
 (10, 115, 98, 0, 0, 24.0, 1.022, 34, 0),
 (0, 124, 56, 13, 105, 21.8, 0.452, 21, 0),
 (0, 74, 52, 10, 36, 27.8, 0.269, 22, 0),
 (0, 97, 64, 36, 100, 36.8, 0.6, 25, 0),
 (8, 120, 0, 0, 0, 30.0, 0.183, 38, 1),
 (6, 154, 78, 41, 140, 46.1, 0.571, 27, 0),
 (1, 144, 82, 40, 0, 41.3, 0.607, 28, 0),
 (0, 137, 70, 38, 0, 33.2, 0.17, 22, 0),
 (0, 119, 66, 27, 0, 38.8, 0.259, 22, 0),
 (7, 136, 90, 0, 0, 29.9, 0.21, 50, 0),

In [30]:
%%sql
SELECT COUNT(*) FROM diebetes

 * sqlite:///database.db
Done.

[(768,)]

Return patient with a BMI greater than 52 and age between 25 and 30

In [31]:
%%sql
SELECT * FROM diebetes WHERE BMI > 52 AND AGE BETWEEN 25 AND 30

 * sqlite:///database.db
Done.

[(0, 162, 76, 56, 100, 53.2, 0.759, 25, 1),
 (1, 88, 30, 42, 99, 55.0, 0.496, 26, 1),
 (0, 129, 110, 46, 130, 67.1, 0.319, 26, 1),
 (5, 115, 98, 0, 0, 52.9, 0.209, 28, 1),
 (0, 180, 78, 63, 14, 59.4, 2.42, 25, 1)]

In [32]:
df.query ('BMI > 52 and 25 <= Age <=30')

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
120,0,162,76,56,100,53.2,0.759,25,1
125,1,88,30,42,99,55.0,0.496,26,1
177,0,129,110,46,130,67.1,0.319,26,1
303,5,115,98,0,0,52.9,0.209,28,1
445,0,180,78,63,14,59.4,2.420,25,1

Execute SQL query to return AGE,GLUCOSE, and Outcomes for patient with Glucose greater than 195

In [34]:
%%sql
SELECT Age, Glucose,Outcome From diebetes WHERE Glucose > 195

 * sqlite:///database.db
Done.

[(41, 196, 1),
 (53, 197, 1),
 (57, 196, 1),
 (31, 197, 0),
 (29, 196, 1),
 (39, 197, 1),
 (28, 198, 1),
 (62, 197, 1),
 (22, 199, 1)]

In [37]:
df.query('Glucose > 195')[['Age','Glucose','Outcome']]

     Age  Glucose  Outcome
4     41      196        1
13    53      197        1
206   57      196        1
228   31      197        0
359   29      196        1
408   39      197        1
561   28      198        1
579   62      197        1
661   22      199        1

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [39]:
%%sql
CREATE TABLE patients (Pregnancies INT,
                          Glucose INT,
                       BloodPressure INT,
                       SkinThickness INT,
                        Insulin INT,
                       BMI DECIMAL(8,2),
                       DiabetesPedigreeFunction DECIMAL(8,2),
                        Age INT,
                       Outcome INT)

 * sqlite:///database.db
Done.

[]

In [40]:
%%sql
SELECT * FROM patients

 * sqlite:///database.db
Done.

[]

In [41]:
%%sql
INSERT INTO patients SELECT Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
FROM diebetes WHERE Age > 50;

 * sqlite:///database.db
81 rows affected.

[]

In [42]:
%%sql
SELECT * FROM patients

 * sqlite:///database.db
Done.

[(2, 197, 70, 45, 543, 30.5, 0.158, 53, 1),
 (8, 125, 96, 0, 0, 0, 0.232, 54, 1),
 (10, 139, 80, 0, 0, 27.1, 1.441, 57, 0),
 (1, 189, 60, 23, 846, 30.1, 0.398, 59, 1),
 (5, 166, 72, 19, 175, 25.8, 0.587, 51, 1),
 (11, 143, 94, 33, 146, 36.6, 0.254, 51, 1),
 (13, 145, 82, 19, 110, 22.2, 0.245, 57, 0),
 (5, 109, 75, 26, 0, 36, 0.546, 60, 0),
 (4, 111, 72, 47, 207, 37.1, 1.39, 56, 1),
 (9, 171, 110, 24, 240, 45.4, 0.721, 54, 1),
 (8, 176, 90, 34, 300, 33.7, 0.467, 58, 1),
 (2, 109, 92, 0, 0, 42.7, 0.845, 54, 0),
 (4, 134, 72, 0, 0, 23.8, 0.277, 60, 1),
 (4, 146, 92, 0, 0, 31.2, 0.539, 61, 1),
 (5, 132, 80, 0, 0, 26.8, 0.186, 69, 0),
 (0, 105, 84, 0, 0, 27.9, 0.741, 62, 1),
 (3, 128, 78, 0, 0, 21.1, 0.268, 55, 0),
 (5, 147, 78, 0, 0, 33.7, 0.218, 65, 0),
 (8, 181, 68, 36, 495, 30.1, 0.615, 60, 1),
 (6, 103, 72, 32, 190, 37.7, 0.324, 55, 0),
 (8, 196, 76, 29, 280, 37.5, 0.605, 57, 1),
 (5, 162, 104, 0, 0, 37.7, 0.151, 52, 1),
 (7, 179, 95, 31, 0, 34.2, 0.164, 60, 0),
 (2, 158, 90, 0, 0, 31.6, 0.805, 66, 1),
 (7, 142, 60, 33, 190, 28.8, 0.687, 61, 0),
 (7, 181, 84, 21, 192, 35.9, 0.586, 51, 1),
 (11, 155, 76, 28, 150, 33.3, 1.353, 51, 1),
 (3, 142, 80, 15, 0, 32.4, 0.2, 63, 0),
 (13, 106, 70, 0, 0, 34.2, 0.251, 52, 0),
 (5, 114, 74, 0, 0, 24.9, 0.744, 57, 0),
 (2, 108, 80, 0, 0, 27, 0.259, 52, 1),
 (7, 136, 74, 26, 135, 26, 0.647, 51, 0),
 (0, 161, 50, 0, 0, 21.9, 0.254, 65, 0),
 (8, 112, 72, 0, 0, 23.6, 0.84, 58, 0),
 (6, 194, 78, 0, 0, 23.5, 0.129, 59, 1),
 (8, 95, 72, 0, 0, 36.8, 0.485, 57, 0),
 (5, 158, 70, 0, 0, 29.8, 0.207, 63, 0),
 (5, 103, 108, 37, 0, 39.2, 0.305, 65, 0),
 (4, 146, 78, 0, 0, 38.5, 0.52, 67, 1),
 (12, 140, 82, 43, 325, 39.2, 0.528, 58, 1),
 (5, 144, 82, 26, 285, 32, 0.452, 58, 1),
 (6, 137, 61, 0, 0, 24.2, 0.151, 55, 0),
 (2, 119, 0, 0, 0, 19.6, 0.832, 72, 0),
 (1, 135, 54, 0, 0, 26.7, 0.687, 62, 0),
 (10, 148, 84, 48, 237, 37.6, 1.001, 51, 1),
 (9, 134, 74, 33, 60, 25.9, 0.46, 81, 0),
 (0, 137, 84, 27, 0, 27.3, 0.231, 59, 0),
 (4, 132, 86, 31, 0, 28, 0.419, 63, 0),
 (0, 173, 78, 32, 265, 46.5, 1.159, 58, 0),
 (8, 194, 80, 0, 0, 26.1, 0.551, 67, 0),
 (6, 166, 74, 0, 0, 26.6, 0.304, 66, 0),
 (7, 195, 70, 33, 145, 25.1, 0.163, 55, 1),
 (8, 120, 78, 0, 0, 25, 0.409, 64, 0),
 (9, 91, 68, 0, 0, 24.2, 0.2, 58, 0),
 (9, 145, 88, 34, 165, 30.3, 0.771, 53, 1),
 (7, 125, 86, 0, 0, 37.6, 0.304, 51, 0),
 (6, 129, 90, 7, 326, 19.6, 0.582, 60, 0),
 (0, 57, 60, 0, 0, 21.7, 0.735, 67, 0),
 (10, 90, 85, 32, 0, 34.9, 0.825, 56, 1),
 (5, 187, 76, 27, 207, 43.6, 1.034, 53, 1),
 (6, 114, 88, 0, 0, 27.8, 0.247, 66, 0),
 (8, 110, 76, 0, 0, 27.8, 0.237, 58, 0),
 (6, 125, 76, 0, 0, 33.8, 0.121, 54, 1),
 (2, 197, 70, 99, 0, 34.7, 0.575, 62, 1),
 (12, 121, 78, 17, 0, 26.5, 0.259, 62, 0),
 (8, 124, 76, 24, 600, 28.7, 0.687, 52, 1),
 (3, 176, 86, 27, 156, 33.3, 1.154, 52, 1),
 (7, 150, 78, 29, 126, 35.2, 0.692, 54, 1),
 (11, 127, 106, 0, 0, 39, 0.19, 51, 0),
 (10, 162, 84, 0, 0, 27.7, 0.182, 54, 0),
 (4, 145, 82, 18, 0, 32.5, 0.235, 70, 1),
 (8, 91, 82, 0, 0, 35.6, 0.587, 68, 0),
 (9, 156, 86, 0, 0, 24.8, 0.23, 53, 1),
 (5, 136, 82, 0, 0, 0, 0.64, 69, 0),
 (1, 168, 88, 29, 0, 35, 0.905, 52, 1),
 (10, 94, 72, 18, 0, 23.1, 0.595, 56, 0),
 (5, 97, 76, 27, 0, 35.6, 0.378, 52, 1),
 (2, 105, 75, 0, 0, 23.3, 0.56, 53, 0),
 (0, 123, 72, 0, 0, 36.3, 0.258, 52, 1),
 (6, 190, 92, 0, 0, 35.5, 0.278, 66, 1),
 (10, 101, 76, 48, 180, 32.9, 0.171, 63, 0)]

In [68]:
%%sql 
ALTER TABLE patients ADD Profile_column VARCHAR(20)

 * sqlite:///database.db
Done.

[]

In [69]:
%%sql 
SELECT * FROM patients

 * sqlite:///database.db
Done.

[(2, 197, 70, 45, 543, 30.5, 0.158, 53, 1, None),
 (8, 125, 96, 0, 0, 0, 0.232, 54, 1, None),
 (10, 139, 80, 0, 0, 27.1, 1.441, 57, 0, None),
 (1, 189, 60, 23, 846, 30.1, 0.398, 59, 1, None),
 (5, 166, 72, 19, 175, 25.8, 0.587, 51, 1, None),
 (11, 143, 94, 33, 146, 36.6, 0.254, 51, 1, None),
 (13, 145, 82, 19, 110, 22.2, 0.245, 57, 0, None),
 (5, 109, 75, 26, 0, 36, 0.546, 60, 0, None),
 (4, 111, 72, 47, 207, 37.1, 1.39, 56, 1, None),
 (9, 171, 110, 24, 240, 45.4, 0.721, 54, 1, None),
 (8, 176, 90, 34, 300, 33.7, 0.467, 58, 1, None),
 (2, 109, 92, 0, 0, 42.7, 0.845, 54, 0, None),
 (4, 134, 72, 0, 0, 23.8, 0.277, 60, 1, None),
 (4, 146, 92, 0, 0, 31.2, 0.539, 61, 1, None),
 (5, 132, 80, 0, 0, 26.8, 0.186, 69, 0, None),
 (0, 105, 84, 0, 0, 27.9, 0.741, 62, 1, None),
 (3, 128, 78, 0, 0, 21.1, 0.268, 55, 0, None),
 (5, 147, 78, 0, 0, 33.7, 0.218, 65, 0, None),
 (8, 181, 68, 36, 495, 30.1, 0.615, 60, 1, None),
 (6, 103, 72, 32, 190, 37.7, 0.324, 55, 0, None),
 (8, 196, 76, 29, 280, 37.5, 0.605, 57, 1, None),
 (5, 162, 104, 0, 0, 37.7, 0.151, 52, 1, None),
 (7, 179, 95, 31, 0, 34.2, 0.164, 60, 0, None),
 (2, 158, 90, 0, 0, 31.6, 0.805, 66, 1, None),
 (7, 142, 60, 33, 190, 28.8, 0.687, 61, 0, None),
 (7, 181, 84, 21, 192, 35.9, 0.586, 51, 1, None),
 (11, 155, 76, 28, 150, 33.3, 1.353, 51, 1, None),
 (3, 142, 80, 15, 0, 32.4, 0.2, 63, 0, None),
 (13, 106, 70, 0, 0, 34.2, 0.251, 52, 0, None),
 (5, 114, 74, 0, 0, 24.9, 0.744, 57, 0, None),
 (2, 108, 80, 0, 0, 27, 0.259, 52, 1, None),
 (7, 136, 74, 26, 135, 26, 0.647, 51, 0, None),
 (0, 161, 50, 0, 0, 21.9, 0.254, 65, 0, None),
 (8, 112, 72, 0, 0, 23.6, 0.84, 58, 0, None),
 (6, 194, 78, 0, 0, 23.5, 0.129, 59, 1, None),
 (8, 95, 72, 0, 0, 36.8, 0.485, 57, 0, None),
 (5, 158, 70, 0, 0, 29.8, 0.207, 63, 0, None),
 (5, 103, 108, 37, 0, 39.2, 0.305, 65, 0, None),
 (4, 146, 78, 0, 0, 38.5, 0.52, 67, 1, None),
 (12, 140, 82, 43, 325, 39.2, 0.528, 58, 1, None),
 (5, 144, 82, 26, 285, 32, 0.452, 58, 1, None),
 (6, 137, 61, 0, 0, 24.2, 0.151, 55, 0, None),
 (2, 119, 0, 0, 0, 19.6, 0.832, 72, 0, None),
 (1, 135, 54, 0, 0, 26.7, 0.687, 62, 0, None),
 (10, 148, 84, 48, 237, 37.6, 1.001, 51, 1, None),
 (9, 134, 74, 33, 60, 25.9, 0.46, 81, 0, None),
 (0, 137, 84, 27, 0, 27.3, 0.231, 59, 0, None),
 (4, 132, 86, 31, 0, 28, 0.419, 63, 0, None),
 (0, 173, 78, 32, 265, 46.5, 1.159, 58, 0, None),
 (8, 194, 80, 0, 0, 26.1, 0.551, 67, 0, None),
 (6, 166, 74, 0, 0, 26.6, 0.304, 66, 0, None),
 (7, 195, 70, 33, 145, 25.1, 0.163, 55, 1, None),
 (8, 120, 78, 0, 0, 25, 0.409, 64, 0, None),
 (9, 91, 68, 0, 0, 24.2, 0.2, 58, 0, None),
 (9, 145, 88, 34, 165, 30.3, 0.771, 53, 1, None),
 (7, 125, 86, 0, 0, 37.6, 0.304, 51, 0, None),
 (6, 129, 90, 7, 326, 19.6, 0.582, 60, 0, None),
 (0, 57, 60, 0, 0, 21.7, 0.735, 67, 0, None),
 (10, 90, 85, 32, 0, 34.9, 0.825, 56, 1, None),
 (5, 187, 76, 27, 207, 43.6, 1.034, 53, 1, None),
 (6, 114, 88, 0, 0, 27.8, 0.247, 66, 0, None),
 (8, 110, 76, 0, 0, 27.8, 0.237, 58, 0, None),
 (6, 125, 76, 0, 0, 33.8, 0.121, 54, 1, None),
 (2, 197, 70, 99, 0, 34.7, 0.575, 62, 1, None),
 (12, 121, 78, 17, 0, 26.5, 0.259, 62, 0, None),
 (8, 124, 76, 24, 600, 28.7, 0.687, 52, 1, None),
 (3, 176, 86, 27, 156, 33.3, 1.154, 52, 1, None),
 (7, 150, 78, 29, 126, 35.2, 0.692, 54, 1, None),
 (11, 127, 106, 0, 0, 39, 0.19, 51, 0, None),
 (10, 162, 84, 0, 0, 27.7, 0.182, 54, 0, None),
 (4, 145, 82, 18, 0, 32.5, 0.235, 70, 1, None),
 (8, 91, 82, 0, 0, 35.6, 0.587, 68, 0, None),
 (9, 156, 86, 0, 0, 24.8, 0.23, 53, 1, None),
 (5, 136, 82, 0, 0, 0, 0.64, 69, 0, None),
 (1, 168, 88, 29, 0, 35, 0.905, 52, 1, None),
 (10, 94, 72, 18, 0, 23.1, 0.595, 56, 0, None),
 (5, 97, 76, 27, 0, 35.6, 0.378, 52, 1, None),
 (2, 105, 75, 0, 0, 23.3, 0.56, 53, 0, None),
 (0, 123, 72, 0, 0, 36.3, 0.258, 52, 1, None),
 (6, 190, 92, 0, 0, 35.5, 0.278, 66, 1, None),
 (10, 101, 76, 48, 180, 32.9, 0.171, 63, 0, None)]

In [70]:
%%sql
UPDATE Patients SET Profile_column = CASE WHEN BMI <=30 THEN 'Normal' ELSE Profile_column END;

 * sqlite:///database.db
81 rows affected.

[]

%%sql
ALTER TABLE patients
DROP COLUMN Profile_column;

In [71]:
%%sql 
SELECT * FROM patients

 * sqlite:///database.db
Done.

[(2, 197, 70, 45, 543, 30.5, 0.158, 53, 1, None),
 (8, 125, 96, 0, 0, 0, 0.232, 54, 1, 'Normal'),
 (10, 139, 80, 0, 0, 27.1, 1.441, 57, 0, 'Normal'),
 (1, 189, 60, 23, 846, 30.1, 0.398, 59, 1, None),
 (5, 166, 72, 19, 175, 25.8, 0.587, 51, 1, 'Normal'),
 (11, 143, 94, 33, 146, 36.6, 0.254, 51, 1, None),
 (13, 145, 82, 19, 110, 22.2, 0.245, 57, 0, 'Normal'),
 (5, 109, 75, 26, 0, 36, 0.546, 60, 0, None),
 (4, 111, 72, 47, 207, 37.1, 1.39, 56, 1, None),
 (9, 171, 110, 24, 240, 45.4, 0.721, 54, 1, None),
 (8, 176, 90, 34, 300, 33.7, 0.467, 58, 1, None),
 (2, 109, 92, 0, 0, 42.7, 0.845, 54, 0, None),
 (4, 134, 72, 0, 0, 23.8, 0.277, 60, 1, 'Normal'),
 (4, 146, 92, 0, 0, 31.2, 0.539, 61, 1, None),
 (5, 132, 80, 0, 0, 26.8, 0.186, 69, 0, 'Normal'),
 (0, 105, 84, 0, 0, 27.9, 0.741, 62, 1, 'Normal'),
 (3, 128, 78, 0, 0, 21.1, 0.268, 55, 0, 'Normal'),
 (5, 147, 78, 0, 0, 33.7, 0.218, 65, 0, None),
 (8, 181, 68, 36, 495, 30.1, 0.615, 60, 1, None),
 (6, 103, 72, 32, 190, 37.7, 0.324, 55, 0, None),
 (8, 196, 76, 29, 280, 37.5, 0.605, 57, 1, None),
 (5, 162, 104, 0, 0, 37.7, 0.151, 52, 1, None),
 (7, 179, 95, 31, 0, 34.2, 0.164, 60, 0, None),
 (2, 158, 90, 0, 0, 31.6, 0.805, 66, 1, None),
 (7, 142, 60, 33, 190, 28.8, 0.687, 61, 0, 'Normal'),
 (7, 181, 84, 21, 192, 35.9, 0.586, 51, 1, None),
 (11, 155, 76, 28, 150, 33.3, 1.353, 51, 1, None),
 (3, 142, 80, 15, 0, 32.4, 0.2, 63, 0, None),
 (13, 106, 70, 0, 0, 34.2, 0.251, 52, 0, None),
 (5, 114, 74, 0, 0, 24.9, 0.744, 57, 0, 'Normal'),
 (2, 108, 80, 0, 0, 27, 0.259, 52, 1, 'Normal'),
 (7, 136, 74, 26, 135, 26, 0.647, 51, 0, 'Normal'),
 (0, 161, 50, 0, 0, 21.9, 0.254, 65, 0, 'Normal'),
 (8, 112, 72, 0, 0, 23.6, 0.84, 58, 0, 'Normal'),
 (6, 194, 78, 0, 0, 23.5, 0.129, 59, 1, 'Normal'),
 (8, 95, 72, 0, 0, 36.8, 0.485, 57, 0, None),
 (5, 158, 70, 0, 0, 29.8, 0.207, 63, 0, 'Normal'),
 (5, 103, 108, 37, 0, 39.2, 0.305, 65, 0, None),
 (4, 146, 78, 0, 0, 38.5, 0.52, 67, 1, None),
 (12, 140, 82, 43, 325, 39.2, 0.528, 58, 1, None),
 (5, 144, 82, 26, 285, 32, 0.452, 58, 1, None),
 (6, 137, 61, 0, 0, 24.2, 0.151, 55, 0, 'Normal'),
 (2, 119, 0, 0, 0, 19.6, 0.832, 72, 0, 'Normal'),
 (1, 135, 54, 0, 0, 26.7, 0.687, 62, 0, 'Normal'),
 (10, 148, 84, 48, 237, 37.6, 1.001, 51, 1, None),
 (9, 134, 74, 33, 60, 25.9, 0.46, 81, 0, 'Normal'),
 (0, 137, 84, 27, 0, 27.3, 0.231, 59, 0, 'Normal'),
 (4, 132, 86, 31, 0, 28, 0.419, 63, 0, 'Normal'),
 (0, 173, 78, 32, 265, 46.5, 1.159, 58, 0, None),
 (8, 194, 80, 0, 0, 26.1, 0.551, 67, 0, 'Normal'),
 (6, 166, 74, 0, 0, 26.6, 0.304, 66, 0, 'Normal'),
 (7, 195, 70, 33, 145, 25.1, 0.163, 55, 1, 'Normal'),
 (8, 120, 78, 0, 0, 25, 0.409, 64, 0, 'Normal'),
 (9, 91, 68, 0, 0, 24.2, 0.2, 58, 0, 'Normal'),
 (9, 145, 88, 34, 165, 30.3, 0.771, 53, 1, None),
 (7, 125, 86, 0, 0, 37.6, 0.304, 51, 0, None),
 (6, 129, 90, 7, 326, 19.6, 0.582, 60, 0, 'Normal'),
 (0, 57, 60, 0, 0, 21.7, 0.735, 67, 0, 'Normal'),
 (10, 90, 85, 32, 0, 34.9, 0.825, 56, 1, None),
 (5, 187, 76, 27, 207, 43.6, 1.034, 53, 1, None),
 (6, 114, 88, 0, 0, 27.8, 0.247, 66, 0, 'Normal'),
 (8, 110, 76, 0, 0, 27.8, 0.237, 58, 0, 'Normal'),
 (6, 125, 76, 0, 0, 33.8, 0.121, 54, 1, None),
 (2, 197, 70, 99, 0, 34.7, 0.575, 62, 1, None),
 (12, 121, 78, 17, 0, 26.5, 0.259, 62, 0, 'Normal'),
 (8, 124, 76, 24, 600, 28.7, 0.687, 52, 1, 'Normal'),
 (3, 176, 86, 27, 156, 33.3, 1.154, 52, 1, None),
 (7, 150, 78, 29, 126, 35.2, 0.692, 54, 1, None),
 (11, 127, 106, 0, 0, 39, 0.19, 51, 0, None),
 (10, 162, 84, 0, 0, 27.7, 0.182, 54, 0, 'Normal'),
 (4, 145, 82, 18, 0, 32.5, 0.235, 70, 1, None),
 (8, 91, 82, 0, 0, 35.6, 0.587, 68, 0, None),
 (9, 156, 86, 0, 0, 24.8, 0.23, 53, 1, 'Normal'),
 (5, 136, 82, 0, 0, 0, 0.64, 69, 0, 'Normal'),
 (1, 168, 88, 29, 0, 35, 0.905, 52, 1, None),
 (10, 94, 72, 18, 0, 23.1, 0.595, 56, 0, 'Normal'),
 (5, 97, 76, 27, 0, 35.6, 0.378, 52, 1, None),
 (2, 105, 75, 0, 0, 23.3, 0.56, 53, 0, 'Normal'),
 (0, 123, 72, 0, 0, 36.3, 0.258, 52, 1, None),
 (6, 190, 92, 0, 0, 35.5, 0.278, 66, 1, None),
 (10, 101, 76, 48, 180, 32.9, 0.171, 63, 0, None)]

In [72]:
%%sql 
SELECT * FROM patients 
WHERE Profile_column = 'Normal'

 * sqlite:///database.db
Done.

[(8, 125, 96, 0, 0, 0, 0.232, 54, 1, 'Normal'),
 (10, 139, 80, 0, 0, 27.1, 1.441, 57, 0, 'Normal'),
 (5, 166, 72, 19, 175, 25.8, 0.587, 51, 1, 'Normal'),
 (13, 145, 82, 19, 110, 22.2, 0.245, 57, 0, 'Normal'),
 (4, 134, 72, 0, 0, 23.8, 0.277, 60, 1, 'Normal'),
 (5, 132, 80, 0, 0, 26.8, 0.186, 69, 0, 'Normal'),
 (0, 105, 84, 0, 0, 27.9, 0.741, 62, 1, 'Normal'),
 (3, 128, 78, 0, 0, 21.1, 0.268, 55, 0, 'Normal'),
 (7, 142, 60, 33, 190, 28.8, 0.687, 61, 0, 'Normal'),
 (5, 114, 74, 0, 0, 24.9, 0.744, 57, 0, 'Normal'),
 (2, 108, 80, 0, 0, 27, 0.259, 52, 1, 'Normal'),
 (7, 136, 74, 26, 135, 26, 0.647, 51, 0, 'Normal'),
 (0, 161, 50, 0, 0, 21.9, 0.254, 65, 0, 'Normal'),
 (8, 112, 72, 0, 0, 23.6, 0.84, 58, 0, 'Normal'),
 (6, 194, 78, 0, 0, 23.5, 0.129, 59, 1, 'Normal'),
 (5, 158, 70, 0, 0, 29.8, 0.207, 63, 0, 'Normal'),
 (6, 137, 61, 0, 0, 24.2, 0.151, 55, 0, 'Normal'),
 (2, 119, 0, 0, 0, 19.6, 0.832, 72, 0, 'Normal'),
 (1, 135, 54, 0, 0, 26.7, 0.687, 62, 0, 'Normal'),
 (9, 134, 74, 33, 60, 25.9, 0.46, 81, 0, 'Normal'),
 (0, 137, 84, 27, 0, 27.3, 0.231, 59, 0, 'Normal'),
 (4, 132, 86, 31, 0, 28, 0.419, 63, 0, 'Normal'),
 (8, 194, 80, 0, 0, 26.1, 0.551, 67, 0, 'Normal'),
 (6, 166, 74, 0, 0, 26.6, 0.304, 66, 0, 'Normal'),
 (7, 195, 70, 33, 145, 25.1, 0.163, 55, 1, 'Normal'),
 (8, 120, 78, 0, 0, 25, 0.409, 64, 0, 'Normal'),
 (9, 91, 68, 0, 0, 24.2, 0.2, 58, 0, 'Normal'),
 (6, 129, 90, 7, 326, 19.6, 0.582, 60, 0, 'Normal'),
 (0, 57, 60, 0, 0, 21.7, 0.735, 67, 0, 'Normal'),
 (6, 114, 88, 0, 0, 27.8, 0.247, 66, 0, 'Normal'),
 (8, 110, 76, 0, 0, 27.8, 0.237, 58, 0, 'Normal'),
 (12, 121, 78, 17, 0, 26.5, 0.259, 62, 0, 'Normal'),
 (8, 124, 76, 24, 600, 28.7, 0.687, 52, 1, 'Normal'),
 (10, 162, 84, 0, 0, 27.7, 0.182, 54, 0, 'Normal'),
 (9, 156, 86, 0, 0, 24.8, 0.23, 53, 1, 'Normal'),
 (5, 136, 82, 0, 0, 0, 0.64, 69, 0, 'Normal'),
 (10, 94, 72, 18, 0, 23.1, 0.595, 56, 0, 'Normal'),
 (2, 105, 75, 0, 0, 23.3, 0.56, 53, 0, 'Normal')]

In [64]:
df_Patients = pd.read_sql("SELECT * FROM Patients",con)

In [65]:
df_Patients

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,197,70,45,543,30.5,0.158,53,1
1,8,125,96,0,0,0.0,0.232,54,1
2,10,139,80,0,0,27.1,1.441,57,0
3,1,189,60,23,846,30.1,0.398,59,1
4,5,166,72,19,175,25.8,0.587,51,1
...,...,...,...,...,...,...,...,...,...
76,5,97,76,27,0,35.6,0.378,52,1
77,2,105,75,0,0,23.3,0.560,53,0
78,0,123,72,0,0,36.3,0.258,52,1
79,6,190,92,0,0,35.5,0.278,66,1
80,10,101,76,48,180,32.9,0.171,63,0

In [66]:
df_Patients['Profile']=df_Patients['BMI'].apply(lambda x: 'Normal' if x<30 else 'None')

In [67]:
df_Patients

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Profile
0,2,197,70,45,543,30.5,0.158,53,1,None
1,8,125,96,0,0,0.0,0.232,54,1,Normal
2,10,139,80,0,0,27.1,1.441,57,0,Normal
3,1,189,60,23,846,30.1,0.398,59,1,None
4,5,166,72,19,175,25.8,0.587,51,1,Normal
...,...,...,...,...,...,...,...,...,...,...
76,5,97,76,27,0,35.6,0.378,52,1,None
77,2,105,75,0,0,23.3,0.560,53,0,Normal
78,0,123,72,0,0,36.3,0.258,52,1,None
79,6,190,92,0,0,35.5,0.278,66,1,None
80,10,101,76,48,180,32.9,0.171,63,0,None