In [2]:
import pandas as pd
data = pd.DataFrame({'level':['junior','Mid-level','Senior'],
                     'salary':[7500,14500,18200],
                     'position':['Data Analyst','Data Engineer','Data Scientiest']})

In [3]:
data.head()

       level  salary         position
0     junior    7500     Data Analyst
1  Mid-level   14500    Data Engineer
2     Senior   18200  Data Scientiest

In [4]:
data.tail(1)

    level  salary         position
2  Senior   18200  Data Scientiest

In [10]:
file_path = 'database.db'

In [21]:
import os
if os.path.exists(file_path):
    try:
        os.remove(file_path)
        print(f"File {file_path} deleted successfully !")
    except Exception as e:
        print(f"Error deleting the file {file_path}.Details:{e}")
else:
    print(f"File {file_path} not found .")

Error deleting the file database.db.Details:[WinError 32] The process cannot access the file because it is being used by another process: 'database.db'

In [22]:
import sqlite3

In [23]:
con = sqlite3.connect('database.db')
data.to_sql('employee', con, if_exists='replace', index=False)
con.close()

In [24]:
%load_ext sql
%config SqlMagic.style = 'ASCII'   # 🔥 THIS LINE FIXES THE ERROR

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [25]:
%sql sqlite:///database.db

In [27]:
%config SqlMagic.autopandas = True

In [30]:
%%sql
SELECT * FROM employee;

 * sqlite:///database.db
Done.

KeyError: 'ASCII'

In [29]:
pip install --upgrade ipython-sql prettytable

Requirement already satisfied: ipython-sql in c:\users\harsh\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\harsh\anaconda3\lib\site-packages (3.17.0)
Requirement already satisfied: ipython in c:\users\harsh\anaconda3\lib\site-packages (from ipython-sql) (9.7.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\harsh\anaconda3\lib\site-packages (from ipython-sql) (2.0.43)
Requirement already satisfied: sqlparse in c:\users\harsh\anaconda3\lib\site-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in c:\users\harsh\anaconda3\lib\site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in c:\users\harsh\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in c:\users\harsh\anaconda3\lib\site-packages (from prettytable) (0.2.13)
Requirement already satisfied: greenlet>=1 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: colorama>=0.4.4 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\harsh\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\harsh\anaconda3\lib\site-packages (from jedi>=0.18.1->ipython->ipython-sql) (0.8.5)
Requirement already satisfied: executing>=1.2.0 in c:\users\harsh\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\harsh\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure_eval in c:\users\harsh\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython->ipython-sql) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [31]:
---to_datetime() -'YYYY-MM-DD'

NameError: name 'to_datetime' is not defined

In [32]:
data = {
    "employee_id": [1, 2, 3, 4, 5, 6],
    "join_date": [
        "2024-01-15",
        "2024-02-20",
        "2024-03-05",
        "2024-04-10",
        "2024-05-18",
        "2024-06-01"
    ],
    "login_time": [
        "09:15:00",
        "10:30:45",
        "08:55:10",
        "09:05:00",
        "11:20:35",
        "07:45:50"
    ],
    "department": [
        "IT",
        "HR",
        "Finance",
        "IT",
        "Sales",
        "HR"
    ]
}

In [33]:
from datetime import datetime,timedelta

In [34]:
df = pd.DataFrame(data)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  6 non-null      int64
 1   join_date    6 non-null      object
 2   login_time   6 non-null      object
 3   department   6 non-null      object
dtypes: int64(1), object(3)
memory usage: 324.0+ bytes

In [36]:
df.head()

   employee_id   join_date login_time department
0            1  2024-01-15   09:15:00         IT
1            2  2024-02-20   10:30:45         HR
2            3  2024-03-05   08:55:10    Finance
3            4  2024-04-10   09:05:00         IT
4            5  2024-05-18   11:20:35      Sales

In [37]:
df['join_date']=pd.to_datetime(df['join_date'])

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  6 non-null      int64
 1   join_date    6 non-null      datetime64[ns]
 2   login_time   6 non-null      object
 3   department   6 non-null      object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 324.0+ bytes

In [55]:
df['datetime_column'] = pd.to_datetime(df['join_date'].dt.date.astype(str) + ' ' + df['login_time'])

In [40]:
df.head()

   employee_id  join_date login_time department     datetime_column
0            1 2024-01-15   09:15:00         IT 2024-01-15 09:15:00
1            2 2024-02-20   10:30:45         HR 2024-02-20 10:30:45
2            3 2024-03-05   08:55:10    Finance 2024-03-05 08:55:10
3            4 2024-04-10   09:05:00         IT 2024-04-10 09:05:00
4            5 2024-05-18   11:20:35      Sales 2024-05-18 11:20:35

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      6 non-null      int64
 1   join_date        6 non-null      datetime64[ns]
 2   login_time       6 non-null      object
 3   department       6 non-null      object
 4   datetime_column  6 non-null      datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(2)
memory usage: 372.0+ bytes

In [57]:
df['datetime_column'] = df['datetime_column'].dt.date.astype(str)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      6 non-null      int64
 1   join_date        6 non-null      datetime64[ns]
 2   login_time       6 non-null      object
 3   department       6 non-null      object
 4   datetime_column  6 non-null      object
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 372.0+ bytes

In [70]:
df['datetime_new'] = pd.to_datetime(df['join_date'].dt.date.astype(str) + ' ' + df['login_time'])

In [71]:
df.head()

,employee_id,join_date,login_time,department,datetime_column,datetime_new
0,1,2024-01-15,09:15:00,IT,2024-01-15,2024-01-15 09:15:00
1,2,2024-02-20,10:30:45,HR,2024-02-20,2024-02-20 10:30:45
2,3,2024-03-05,08:55:10,Finance,2024-03-05,2024-03-05 08:55:10
3,4,2024-04-10,09:05:00,IT,2024-04-10,2024-04-10 09:05:00
4,5,2024-05-18,11:20:35,Sales,2024-05-18,2024-05-18 11:20:35

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      6 non-null      int64
 1   join_date        6 non-null      datetime64[ns]
 2   login_time       6 non-null      object
 3   department       6 non-null      object
 4   datetime_column  6 non-null      object
 5   datetime_new     6 non-null      object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 420.0+ bytes

In [78]:
df['datetime_new1'] = pd.to_datetime(df['join_date'].dt.date.astype(str) + ' ' + df['login_time'])

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      6 non-null      int64
 1   join_date        6 non-null      datetime64[ns]
 2   login_time       6 non-null      object
 3   department       6 non-null      object
 4   datetime_column  6 non-null      object
 5   datetime_new     6 non-null      datetime64[ns]
 6   datetime_new1    6 non-null      datetime64[ns]
dtypes: datetime64[ns](3), int64(1), object(3)
memory usage: 468.0+ bytes

In [80]:
df.head()

,employee_id,join_date,login_time,department,datetime_column,datetime_new,datetime_new1
0,1,2024-01-15,09:15:00,IT,2024-01-15,2024-01-15 09:15:00,2024-01-15 09:15:00
1,2,2024-02-20,10:30:45,HR,2024-02-20,2024-02-20 10:30:45,2024-02-20 10:30:45
2,3,2024-03-05,08:55:10,Finance,2024-03-05,2024-03-05 08:55:10,2024-03-05 08:55:10
3,4,2024-04-10,09:05:00,IT,2024-04-10,2024-04-10 09:05:00,2024-04-10 09:05:00
4,5,2024-05-18,11:20:35,Sales,2024-05-18,2024-05-18 11:20:35,2024-05-18 11:20:35

In [81]:
df['datetime_new1'] = df['datetime_new1'].dt.year.astype(str)

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      6 non-null      int64
 1   join_date        6 non-null      datetime64[ns]
 2   login_time       6 non-null      object
 3   department       6 non-null      object
 4   datetime_column  6 non-null      object
 5   datetime_new     6 non-null      datetime64[ns]
 6   datetime_new1    6 non-null      object
dtypes: datetime64[ns](2), int64(1), object(4)
memory usage: 468.0+ bytes

In [83]:
df.head()

,employee_id,join_date,login_time,department,datetime_column,datetime_new,datetime_new1
0,1,2024-01-15,09:15:00,IT,2024-01-15,2024-01-15 09:15:00,2024
1,2,2024-02-20,10:30:45,HR,2024-02-20,2024-02-20 10:30:45,2024
2,3,2024-03-05,08:55:10,Finance,2024-03-05,2024-03-05 08:55:10,2024
3,4,2024-04-10,09:05:00,IT,2024-04-10,2024-04-10 09:05:00,2024
4,5,2024-05-18,11:20:35,Sales,2024-05-18,2024-05-18 11:20:35,2024

In [87]:
df['YEAR']=df['datetime_new'].dt.year

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   employee_id      6 non-null      int64
 1   join_date        6 non-null      datetime64[ns]
 2   login_time       6 non-null      object
 3   department       6 non-null      object
 4   datetime_column  6 non-null      object
 5   datetime_new     6 non-null      datetime64[ns]
 6   datetime_new1    6 non-null      object
 7   YEAR             6 non-null      int32
dtypes: datetime64[ns](2), int32(1), int64(1), object(4)
memory usage: 492.0+ bytes

In [89]:
df.head()

,employee_id,join_date,login_time,department,datetime_column,datetime_new,datetime_new1,YEAR
0,1,2024-01-15,09:15:00,IT,2024-01-15,2024-01-15 09:15:00,2024,2024
1,2,2024-02-20,10:30:45,HR,2024-02-20,2024-02-20 10:30:45,2024,2024
2,3,2024-03-05,08:55:10,Finance,2024-03-05,2024-03-05 08:55:10,2024,2024
3,4,2024-04-10,09:05:00,IT,2024-04-10,2024-04-10 09:05:00,2024,2024
4,5,2024-05-18,11:20:35,Sales,2024-05-18,2024-05-18 11:20:35,2024,2024

In [90]:
df['MONTH']=df['datetime_new'].dt.month

In [91]:
df.head()

,employee_id,join_date,login_time,department,datetime_column,datetime_new,datetime_new1,YEAR,MONTH
0,1,2024-01-15,09:15:00,IT,2024-01-15,2024-01-15 09:15:00,2024,2024,1
1,2,2024-02-20,10:30:45,HR,2024-02-20,2024-02-20 10:30:45,2024,2024,2
2,3,2024-03-05,08:55:10,Finance,2024-03-05,2024-03-05 08:55:10,2024,2024,3
3,4,2024-04-10,09:05:00,IT,2024-04-10,2024-04-10 09:05:00,2024,2024,4
4,5,2024-05-18,11:20:35,Sales,2024-05-18,2024-05-18 11:20:35,2024,2024,5

In [94]:
df['DAY']=df['datetime_new'].dt.day

In [95]:
df.head()

,employee_id,join_date,login_time,department,datetime_column,datetime_new,datetime_new1,YEAR,MONTH,DAY
0,1,2024-01-15,09:15:00,IT,2024-01-15,2024-01-15 09:15:00,2024,2024,1,15
1,2,2024-02-20,10:30:45,HR,2024-02-20,2024-02-20 10:30:45,2024,2024,2,20
2,3,2024-03-05,08:55:10,Finance,2024-03-05,2024-03-05 08:55:10,2024,2024,3,5
3,4,2024-04-10,09:05:00,IT,2024-04-10,2024-04-10 09:05:00,2024,2024,4,10
4,5,2024-05-18,11:20:35,Sales,2024-05-18,2024-05-18 11:20:35,2024,2024,5,18

In [96]:
df['WeekDays']=df['datetime_new'].dt.weekday

In [97]:
df.head()

,employee_id,join_date,login_time,department,datetime_column,datetime_new,datetime_new1,YEAR,MONTH,DAY,WeekDays
0,1,2024-01-15,09:15:00,IT,2024-01-15,2024-01-15 09:15:00,2024,2024,1,15,0
1,2,2024-02-20,10:30:45,HR,2024-02-20,2024-02-20 10:30:45,2024,2024,2,20,1
2,3,2024-03-05,08:55:10,Finance,2024-03-05,2024-03-05 08:55:10,2024,2024,3,5,1
3,4,2024-04-10,09:05:00,IT,2024-04-10,2024-04-10 09:05:00,2024,2024,4,10,2
4,5,2024-05-18,11:20:35,Sales,2024-05-18,2024-05-18 11:20:35,2024,2024,5,18,5

In [98]:
df = pd.DataFrame(data)

In [99]:
df

   employee_id   join_date login_time department
0            1  2024-01-15   09:15:00         IT
1            2  2024-02-20   10:30:45         HR
2            3  2024-03-05   08:55:10    Finance
3            4  2024-04-10   09:05:00         IT
4            5  2024-05-18   11:20:35      Sales
5            6  2024-06-01   07:45:50         HR

In [100]:
df['join_date'] = pd.to_datetime(df['join_date'])

In [102]:
df['Next_joining_date']=df['join_date']+pd.Timedelta(days=5)

In [103]:
df

   employee_id  join_date login_time department Next_joining_date
0            1 2024-01-15   09:15:00         IT        2024-01-20
1            2 2024-02-20   10:30:45         HR        2024-02-25
2            3 2024-03-05   08:55:10    Finance        2024-03-10
3            4 2024-04-10   09:05:00         IT        2024-04-15
4            5 2024-05-18   11:20:35      Sales        2024-05-23
5            6 2024-06-01   07:45:50         HR        2024-06-06

In [108]:
df['previous_joining_date']=df['join_date']-pd.Timedelta(days=5)

In [109]:
df

,employee_id,join_date,login_time,department,Next_joining_date,previous_joining_date
0,1,2024-01-15,09:15:00,IT,2024-01-20,2024-01-10
1,2,2024-02-20,10:30:45,HR,2024-02-25,2024-02-15
2,3,2024-03-05,08:55:10,Finance,2024-03-10,2024-02-29
3,4,2024-04-10,09:05:00,IT,2024-04-15,2024-04-05
4,5,2024-05-18,11:20:35,Sales,2024-05-23,2024-05-13
5,6,2024-06-01,07:45:50,HR,2024-06-06,2024-05-27

In [114]:
from pandas.tseries.offsets import DateOffset
df['future_month'] = df['join_date'] + pd.DateOffset(months=5)

In [115]:
df

,employee_id,join_date,login_time,department,Next_joining_date,previous_joining_date,future_month
0,1,2024-01-15,09:15:00,IT,2024-01-20,2024-01-10,2024-06-15
1,2,2024-02-20,10:30:45,HR,2024-02-25,2024-02-15,2024-07-20
2,3,2024-03-05,08:55:10,Finance,2024-03-10,2024-02-29,2024-08-05
3,4,2024-04-10,09:05:00,IT,2024-04-15,2024-04-05,2024-09-10
4,5,2024-05-18,11:20:35,Sales,2024-05-23,2024-05-13,2024-10-18
5,6,2024-06-01,07:45:50,HR,2024-06-06,2024-05-27,2024-11-01

In [116]:
df['future_year'] = df['join_date'] + pd.DateOffset(years=1)

In [117]:
df

,employee_id,join_date,login_time,department,Next_joining_date,previous_joining_date,future_month,future_year
0,1,2024-01-15,09:15:00,IT,2024-01-20,2024-01-10,2024-06-15,2025-01-15
1,2,2024-02-20,10:30:45,HR,2024-02-25,2024-02-15,2024-07-20,2025-02-20
2,3,2024-03-05,08:55:10,Finance,2024-03-10,2024-02-29,2024-08-05,2025-03-05
3,4,2024-04-10,09:05:00,IT,2024-04-15,2024-04-05,2024-09-10,2025-04-10
4,5,2024-05-18,11:20:35,Sales,2024-05-23,2024-05-13,2024-10-18,2025-05-18
5,6,2024-06-01,07:45:50,HR,2024-06-06,2024-05-27,2024-11-01,2025-06-01

In [122]:
df['formatted_date'] = df['join_date'].dt.strftime('%d-%m-%Y')

In [123]:
df

,employee_id,join_date,login_time,department,Next_joining_date,previous_joining_date,future_month,future_year,formatted_date
0,1,2024-01-15,09:15:00,IT,2024-01-20,2024-01-10,2024-06-15,2025-01-15,15-01-2024
1,2,2024-02-20,10:30:45,HR,2024-02-25,2024-02-15,2024-07-20,2025-02-20,20-02-2024
2,3,2024-03-05,08:55:10,Finance,2024-03-10,2024-02-29,2024-08-05,2025-03-05,05-03-2024
3,4,2024-04-10,09:05:00,IT,2024-04-15,2024-04-05,2024-09-10,2025-04-10,10-04-2024
4,5,2024-05-18,11:20:35,Sales,2024-05-23,2024-05-13,2024-10-18,2025-05-18,18-05-2024
5,6,2024-06-01,07:45:50,HR,2024-06-06,2024-05-27,2024-11-01,2025-06-01,01-06-2024

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            6 non-null      int64
 1   join_date              6 non-null      datetime64[ns]
 2   login_time             6 non-null      object
 3   department             6 non-null      object
 4   Next_joining_date      6 non-null      datetime64[ns]
 5   previous_joining_date  6 non-null      datetime64[ns]
 6   future_month           6 non-null      datetime64[ns]
 7   future_year            6 non-null      datetime64[ns]
 8   formatted_date         6 non-null      object
dtypes: datetime64[ns](5), int64(1), object(3)
memory usage: 564.0+ bytes

In [130]:
df['join_date_new']=pd.to_datetime(df['formatted_date'],format='%d-%m-%Y')

In [131]:
df

,employee_id,join_date,login_time,department,Next_joining_date,previous_joining_date,future_month,future_year,formatted_date,join_date_new
0,1,2024-01-15,09:15:00,IT,2024-01-20,2024-01-10,2024-06-15,2025-01-15,15-01-2024,2024-01-15
1,2,2024-02-20,10:30:45,HR,2024-02-25,2024-02-15,2024-07-20,2025-02-20,20-02-2024,2024-02-20
2,3,2024-03-05,08:55:10,Finance,2024-03-10,2024-02-29,2024-08-05,2025-03-05,05-03-2024,2024-03-05
3,4,2024-04-10,09:05:00,IT,2024-04-15,2024-04-05,2024-09-10,2025-04-10,10-04-2024,2024-04-10
4,5,2024-05-18,11:20:35,Sales,2024-05-23,2024-05-13,2024-10-18,2025-05-18,18-05-2024,2024-05-18
5,6,2024-06-01,07:45:50,HR,2024-06-06,2024-05-27,2024-11-01,2025-06-01,01-06-2024,2024-06-01

In [134]:
df['is_leap_df']=df['join_date_new'].dt.is_leap_year

In [135]:
df

,employee_id,join_date,login_time,department,Next_joining_date,previous_joining_date,future_month,future_year,formatted_date,join_date_new,is_leap_df
0,1,2024-01-15,09:15:00,IT,2024-01-20,2024-01-10,2024-06-15,2025-01-15,15-01-2024,2024-01-15,True
1,2,2024-02-20,10:30:45,HR,2024-02-25,2024-02-15,2024-07-20,2025-02-20,20-02-2024,2024-02-20,True
2,3,2024-03-05,08:55:10,Finance,2024-03-10,2024-02-29,2024-08-05,2025-03-05,05-03-2024,2024-03-05,True
3,4,2024-04-10,09:05:00,IT,2024-04-15,2024-04-05,2024-09-10,2025-04-10,10-04-2024,2024-04-10,True
4,5,2024-05-18,11:20:35,Sales,2024-05-23,2024-05-13,2024-10-18,2025-05-18,18-05-2024,2024-05-18,True
5,6,2024-06-01,07:45:50,HR,2024-06-06,2024-05-27,2024-11-01,2025-06-01,01-06-2024,2024-06-01,True

In [136]:
!pip install snowflake-connector-python

Collecting snowflake-connector-python
  Downloading snowflake_connector_python-4.1.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
Collecting asn1crypto<2.0.0,>0.24.0 (from snowflake-connector-python)
  Downloading asn1crypto-1.5.1-py2.py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: cryptography>=44.0.1 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (46.0.3)
Requirement already satisfied: pyOpenSSL<26.0.0,>=24.0.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (25.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (2.10.1)
Requirement already satisfied: pytz in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (2025.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (2.32.5)
Requirement already satisfied: packaging in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (3.4.4)
Requirement already satisfied: idna<4,>=3.7 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (3.11)
Requirement already satisfied: certifi>=2024.7.4 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (2025.11.12)
Requirement already satisfied: typing_extensions<5,>=4.3 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (4.15.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (3.20.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (4.5.0)
Requirement already satisfied: tomlkit in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (0.13.3)
Collecting boto3>=1.24 (from snowflake-connector-python)
  Downloading boto3-1.42.21-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: botocore>=1.24 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python) (1.40.46)
Requirement already satisfied: cffi>=2.0.0 in c:\users\harsh\anaconda3\lib\site-packages (from cryptography>=44.0.1->snowflake-connector-python) (2.0.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\harsh\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.4->snowflake-connector-python) (2.5.0)
Collecting botocore>=1.24 (from snowflake-connector-python)
  Downloading botocore-1.42.21-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\harsh\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (1.0.1)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3>=1.24->snowflake-connector-python)
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\harsh\anaconda3\lib\site-packages (from botocore>=1.24->snowflake-connector-python) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\harsh\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.24->snowflake-connector-python) (1.17.0)
Requirement already satisfied: pycparser in c:\users\harsh\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=44.0.1->snowflake-connector-python) (2.23)
Downloading snowflake_connector_python-4.1.1-cp313-cp313-win_amd64.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 8.2 MB/s  0:00:00
Downloading asn1crypto-1.5.1-py2.py3-none-any.whl (105 kB)
Downloading boto3-1.42.21-py3-none-any.whl (140 kB)
Downloading botocore-1.42.21-py3-none-any.whl (14.6 MB)
   ---------------------------------------- 0.0/14.6 MB ? eta -:--:--
   -- ------------------------------------- 1.0/14.6 MB 7.3 MB/s eta 0:00:02
   -------- ------------------------------- 3.1/14.6 MB 7.9 MB/s eta 0:00:02
   ------------ --------------------------- 4.5/14.6 MB 7.1 MB/s eta 0:00:02
   ---------------- ----------------------- 6.0/14.6 MB 7.4 MB/s eta 0:00:02
   -------------------- ------------------- 7.6/14.6 MB 7.5 MB/s eta 0:00:01
   ------------------------ --------------- 8.9/14.6 MB 7.1 MB/s eta 0:00:01
   ---------------------------- ----------- 10.2/14.6 MB 7.0 MB/s eta 0:00:01
   --------------------------------- ------ 12.3/14.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  14.4/14.6 MB 7.6 MB/s eta 0:00:01
   ---------------------------------------- 14.6/14.6 MB 7.3 MB/s  0:00:02
Downloading s3transfer-0.16.0-py3-none-any.whl (86 kB)
Installing collected packages: asn1crypto, botocore, s3transfer, boto3, snowflake-connector-python

   ---------------------------------------- 0/5 [asn1crypto]
  Attempting uninstall: botocore
   ---------------------------------------- 0/5 [asn1crypto]
    Found existing installation: botocore 1.40.46
   ---------------------------------------- 0/5 [asn1crypto]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
    Uninstalling botocore-1.40.46:
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
      Successfully uninstalled botocore-1.40.46
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   -------- ------------------------------- 1/5 [botocore]
   ---------------- ----------------------- 2/5 [s3transfer]
   ------------------------ --------------- 3/5 [boto3]
   ------------------------ --------------- 3/5 [boto3]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   -------------------------------- ------- 4/5 [snowflake-connector-python]
   ---------------------------------------- 5/5 [snowflake-connector-python]

Successfully installed asn1crypto-1.5.1 boto3-1.42.21 botocore-1.42.21 s3transfer-0.16.0 snowflake-connector-python-4.1.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.25.0 requires botocore<1.40.50,>=1.40.46, but you have botocore 1.42.21 which is incompatible.

In [137]:
!pip install snowflake-sqlalchemy

Collecting snowflake-sqlalchemy
  Downloading snowflake_sqlalchemy-1.8.2-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: snowflake-connector-python<5.0.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-sqlalchemy) (4.1.1)
Requirement already satisfied: sqlalchemy>=1.4.19 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-sqlalchemy) (2.0.43)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (1.5.1)
Requirement already satisfied: cryptography>=44.0.1 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (46.0.3)
Requirement already satisfied: pyOpenSSL<26.0.0,>=24.0.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (25.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2.10.1)
Requirement already satisfied: pytz in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2025.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2.32.5)
Requirement already satisfied: packaging in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (3.4.4)
Requirement already satisfied: idna<4,>=3.7 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (3.11)
Requirement already satisfied: certifi>=2024.7.4 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2025.11.12)
Requirement already satisfied: typing_extensions<5,>=4.3 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (4.15.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (3.20.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (4.5.0)
Requirement already satisfied: tomlkit in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (0.13.3)
Requirement already satisfied: boto3>=1.24 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (1.42.21)
Requirement already satisfied: botocore>=1.24 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (1.42.21)
Requirement already satisfied: cffi>=2.0.0 in c:\users\harsh\anaconda3\lib\site-packages (from cryptography>=44.0.1->snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2.0.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\harsh\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.4->snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2.5.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\harsh\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\harsh\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\harsh\anaconda3\lib\site-packages (from botocore>=1.24->snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\harsh\anaconda3\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.24->snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (1.17.0)
Requirement already satisfied: pycparser in c:\users\harsh\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=44.0.1->snowflake-connector-python<5.0.0->snowflake-sqlalchemy) (2.23)
Requirement already satisfied: greenlet>=1 in c:\users\harsh\anaconda3\lib\site-packages (from sqlalchemy>=1.4.19->snowflake-sqlalchemy) (3.2.4)
Downloading snowflake_sqlalchemy-1.8.2-py3-none-any.whl (72 kB)
Installing collected packages: snowflake-sqlalchemy
Successfully installed snowflake-sqlalchemy-1.8.2

In [138]:
!pip install "snowflake-connector-python[pandas]"

Requirement already satisfied: snowflake-connector-python[pandas] in c:\users\harsh\anaconda3\lib\site-packages (4.1.1)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (1.5.1)
Requirement already satisfied: cryptography>=44.0.1 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (46.0.3)
Requirement already satisfied: pyOpenSSL<26.0.0,>=24.0.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (25.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.10.1)
Requirement already satisfied: pytz in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2025.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.32.5)
Requirement already satisfied: packaging in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (3.4.4)
Requirement already satisfied: idna<4,>=3.7 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (3.11)
Requirement already satisfied: certifi>=2024.7.4 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2025.11.12)
Requirement already satisfied: typing_extensions<5,>=4.3 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (4.15.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (3.20.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (4.5.0)
Requirement already satisfied: tomlkit in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (0.13.3)
Requirement already satisfied: boto3>=1.24 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (1.42.21)
Requirement already satisfied: botocore>=1.24 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (1.42.21)
Requirement already satisfied: pandas<3.0.0,>=2.1.2 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (2.3.3)
Requirement already satisfied: pyarrow>=14.0.1 in c:\users\harsh\anaconda3\lib\site-packages (from snowflake-connector-python[pandas]) (21.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\harsh\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.1.2->snowflake-connector-python[pandas]) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harsh\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.1.2->snowflake-connector-python[pandas]) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\harsh\anaconda3\lib\site-packages (from pandas<3.0.0,>=2.1.2->snowflake-connector-python[pandas]) (2025.2)
Requirement already satisfied: cffi>=2.0.0 in c:\users\harsh\anaconda3\lib\site-packages (from cryptography>=44.0.1->snowflake-connector-python[pandas]) (2.0.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\harsh\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.4->snowflake-connector-python[pandas]) (2.5.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\harsh\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python[pandas]) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\harsh\anaconda3\lib\site-packages (from boto3>=1.24->snowflake-connector-python[pandas]) (0.16.0)
Requirement already satisfied: six>=1.5 in c:\users\harsh\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.1.2->snowflake-connector-python[pandas]) (1.17.0)
Requirement already satisfied: pycparser in c:\users\harsh\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=44.0.1->snowflake-connector-python[pandas]) (2.23)

In [1]:
import snowflake.connector
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import getpass
import seaborn as sns 
%matplotlib inline
import seaborn as sns
import statsmodels.api as sm

from sqlalchemy import create_engine
from sqlalchemy.engine import URL
from snowflake.connector.pandas_tools import write_pandas

In [2]:
# Establish the connection
conn = snowflake.connector.connect(
    account= 'wfdmzkv-nr55574',
    user='HARSH3098',
    password = getpass.getpass('Your Snowflake Password: '),
    ##'A6jha@90',
    warehouse='COMPUTE_WH',
    database='eda',
    schema='eda_schema',
    role='ACCOUNTADMIN'
)

# Test the connection
cursor = conn.cursor()
cursor.execute("SELECT CURRENT_VERSION()")
print(cursor.fetchone())

Your Snowflake Password:  ········

('9.39.2',)

In [3]:
cur = conn.cursor()

In [4]:
cur.execute("SELECT * FROM NHANES_MANUAL_UPLOAD")

In [5]:
NHANES_DATA_RAW = cur.fetch_pandas_all()

In [6]:
NHANES_DATA_RAW

,SEQN,ALQ101,ALQ110,ALQ130,SMQ020,RIAGENDR,RIDAGEYR,RIDRETH1,DMDCITZN,DMDEDUC2,...,BPXSY2,BPXDI2,BMXWT,BMXHT,BMXBMI,BMXLEG,BMXARML,BMXARMC,BMXWAIST,HIQ210
0,83732,1.0,NaN,1.0,1,1,62,3,1.0,5.0,...,124.0,64.0,94.8,184.5,27.8,43.3,43.6,35.9,101.1,2.0
1,83733,1.0,NaN,6.0,1,1,53,3,2.0,3.0,...,140.0,88.0,90.4,171.4,30.8,38.0,40.0,33.2,107.9,NaN
2,83734,1.0,NaN,NaN,1,1,78,3,1.0,3.0,...,132.0,44.0,83.4,170.1,28.8,35.6,37.0,31.0,116.5,2.0
3,83735,2.0,1.0,1.0,2,2,56,3,1.0,5.0,...,134.0,68.0,109.8,160.9,42.4,38.5,37.7,38.3,110.1,2.0
4,83736,2.0,1.0,1.0,2,2,42,4,1.0,4.0,...,114.0,54.0,55.2,164.9,20.3,37.4,36.0,27.2,80.4,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5730,93695,2.0,2.0,NaN,1,2,76,3,1.0,3.0,...,112.0,46.0,59.1,165.8,21.5,38.2,37.0,29.5,95.0,2.0
5731,93696,2.0,2.0,NaN,2,1,26,3,1.0,5.0,...,116.0,76.0,112.1,182.2,33.8,43.4,41.8,42.3,110.2,2.0
5732,93697,1.0,NaN,1.0,1,2,80,3,1.0,4.0,...,146.0,58.0,71.7,152.2,31.0,31.3,37.5,28.8,NaN,2.0
5733,93700,NaN,NaN,NaN,1,1,35,3,2.0,1.0,...,106.0,66.0,78.2,173.3,26.0,40.3,37.5,30.6,98.9,2.0
5734,93702,1.0,NaN,2.0,2,2,24,3,1.0,5.0,...,114.0,68.0,58.3,165.0,21.4,38.2,33.5,26.2,72.5,2.0

In [7]:
NHANES_DATA_RAW.shape

(5735, 28)

In [8]:
# Isolate the column 
data = NHANES_DATA_RAW.loc[:,('SEQN','SMQ020', 'RIAGENDR', 'RIDAGEYR','DMDEDUC2','BMXWT', 'BMXHT', 'BMXBMI')]
data.head()

    SEQN  SMQ020  RIAGENDR  RIDAGEYR  DMDEDUC2  BMXWT  BMXHT  BMXBMI
0  83732       1         1        62       5.0   94.8  184.5    27.8
1  83733       1         1        53       3.0   90.4  171.4    30.8
2  83734       1         1        78       3.0   83.4  170.1    28.8
3  83735       2         2        56       5.0  109.8  160.9    42.4
4  83736       2         2        42       4.0   55.2  164.9    20.3

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5735 entries, 0 to 5734
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SEQN      5735 non-null   int32
 1   SMQ020    5735 non-null   int8
 2   RIAGENDR  5735 non-null   int8
 3   RIDAGEYR  5735 non-null   int8
 4   DMDEDUC2  5474 non-null   float64
 5   BMXWT     5666 non-null   float64
 6   BMXHT     5673 non-null   float64
 7   BMXBMI    5662 non-null   float64
dtypes: float64(4), int32(1), int8(3)
memory usage: 218.6 KB

In [11]:
# Change the column names to ease the use
data.columns = ['seqn','smoking','gender', 'age','education','weight','height','bmi']

In [12]:
data.head()

    seqn  smoking  gender  age  education  weight  height   bmi
0  83732        1       1   62        5.0    94.8   184.5  27.8
1  83733        1       1   53        3.0    90.4   171.4  30.8
2  83734        1       1   78        3.0    83.4   170.1  28.8
3  83735        2       2   56        5.0   109.8   160.9  42.4
4  83736        2       2   42        4.0    55.2   164.9  20.3

In [13]:
data.shape

(5735, 8)

In [14]:
# Check for duplicates
duplicateRowsDF = data[data.duplicated()]
duplicateRowsDF

Empty DataFrame
Columns: [seqn, smoking, gender, age, education, weight, height, bmi]
Index: []

In [15]:
data.drop(columns = 'seqn', inplace = True)

In [16]:
data.head()

   smoking  gender  age  education  weight  height   bmi
0        1       1   62        5.0    94.8   184.5  27.8
1        1       1   53        3.0    90.4   171.4  30.8
2        1       1   78        3.0    83.4   170.1  28.8
3        2       2   56        5.0   109.8   160.9  42.4
4        2       2   42        4.0    55.2   164.9  20.3

In [17]:
# Check for missing data
data.isnull().sum()

smoking        0
gender         0
age            0
education    261
weight        69
height        62
bmi           73
dtype: int64

In [18]:
data.shape

(5735, 7)

In [19]:
# Drop the missing values
data.dropna(inplace = True)

In [20]:
data.shape

(5406, 7)

In [23]:
data.head()

   smoking  gender  age  education  weight  height   bmi
0        1       1   62        5.0    94.8   184.5  27.8
1        1       1   53        3.0    90.4   171.4  30.8
2        1       1   78        3.0    83.4   170.1  28.8
3        2       2   56        5.0   109.8   160.9  42.4
4        2       2   42        4.0    55.2   164.9  20.3

In [24]:
cur.close()

False

In [25]:
conn.close()

In [30]:
from snowflake.sqlalchemy import URL
from sqlalchemy import create_engine, text
import getpass

engine = create_engine(
    URL(
        account='wfdmzkv-nr55574',
        user='HARSH3098',
        password=getpass.getpass('Your Snowflake Password: '),
        warehouse='COMPUTE_WH',
        database='eda',
        schema='eda_schema',
        role='ACCOUNTADMIN'
    )
)

try:
    with engine.connect() as connection:
        result = connection.execute(text("SELECT current_version()"))
        print(result.scalar())
finally:
    engine.dispose()

Your Snowflake Password:  ········

9.39.2

In [31]:
# Push DataFrame to Snowflake
try:
    data.to_sql('NHANES_CLEANED_DATA', con=engine, index=False, if_exists='append', method='multi')
    print("Data uploaded successfully!")
except Exception as e:
    print(f"Error occurred: {e}")

C:\Users\harsh\AppData\Local\Temp\ipykernel_22388\2943389064.py:3: UserWarning: The provided table name 'NHANES_CLEANED_DATA' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  data.to_sql('NHANES_CLEANED_DATA', con=engine, index=False, if_exists='append', method='multi')

Data uploaded successfully!

In [33]:
# Verify the Upload
with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM NHANES_CLEANED_DATA LIMIT 10"))
    for row in result:
        print(row)

(1, 1, 62, 5.0, 94.8, 184.5, 27.8)
(1, 1, 53, 3.0, 90.4, 171.4, 30.8)
(1, 1, 78, 3.0, 83.4, 170.1, 28.8)
(2, 2, 56, 5.0, 109.8, 160.9, 42.4)
(2, 2, 42, 4.0, 55.2, 164.9, 20.3)
(2, 2, 72, 2.0, 64.4, 150.0, 28.6)
(1, 1, 22, 4.0, 76.6, 165.4, 28.0)
(2, 2, 32, 4.0, 64.5, 151.3, 28.2)
(2, 1, 56, 3.0, 108.3, 179.4, 33.6)
(1, 1, 46, 5.0, 86.2, 176.7, 27.6)